### PR TITLE
[15.0][MIG] account_payment_purchase: Migration to 15.0

### PR DESCRIPTION
**Pull request by aisopuro**
Rebased version of #928 

All credit to @airlessproject for the commits.

### CODE REVIEW

**Comment by ao-landoo** [comment]
Can you squash the last 3 commits?

**Comment by aisopuro** [comment]
> Can you squash the last 3 commits?

I'll squash the last 2, otherwise I can't keep author information properly.

**Comment by aisopuro** [comment]
@ao-landoo squashed and pushed

**Review by Shide — APPROVED** [review]

**Comment by pedrobaeza** [comment]
What happen with #877 and #928 ?

**Comment by pedrobaeza** [comment]
OK, seen the thread and closed previous attempts. Let's merge this one:

/ocabot merge nobump
/ocabot migration account_payment_purchase

**Pull request merged**
