### PR TITLE
[16.0][MIG] account_payment_sale

### PR DESCRIPTION
**Pull request by atchuthan**
Depends on https://github.com/OCA/bank-payment/pull/969

cc: @SodexisTeam

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Hi @atchuthan

Can you rebase please now that dependency has been merge ?

**Comment by atchuthan** [comment]
> Hi @atchuthan
> 
> Can you rebase please now that dependency has been merge ?

rebase done

**Comment by alexis-via** [comment]
Great work, thank you. I'll approve it once you'll have integrated my PR https://github.com/sodexis/bank-payment/pull/1 on this PR. It adds payment_mode_id to sale.report.

**Comment by atchuthan** [comment]
> Great work, thank you. I'll approve it once you'll have integrated my PR [sodexis#1](https://github.com/sodexis/bank-payment/pull/1) on this PR. It adds payment_mode_id to sale.report.

@alexis-via Done

**Review by florian-dacosta — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Comment by rousseldenis** [comment]
@alexis-via I think there is a missing block here: payment_mode_id should be added in invoice grouping here: https://github.com/odoo/odoo/blob/16.0/addons/sale/models/sale_order.py#L1045C5-L1046C59

What do you think ?

**Pull request closed without merging**
