### PR TITLE
[13.0][MIG] account_banking_sepa_direct_debit

### PR DESCRIPTION
**Pull request by misern2**
~~Depends on  #670~~

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Hi @misern2 ,

https://github.com/OCA/bank-payment/pull/670 has been superseded by https://github.com/OCA/bank-payment/pull/698 and this last one has been merged. 

You can continue with your PR.

Could you have a look at the checks? Thanks!

**Comment by misern2** [comment]
@HaraldPanten Rebase done.

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Hi @misern2 ,

It's not working 100% OK. I prepared the direct debit order, after making sure that I had all the parameters properly set (bank accounts, mandates, payment mode, invoices, etc.).

I found an issue:

After the configuration of a debit order I generated my .xml file, but it's not an .xml file what user can download from the next step screen, using the download link. Please, see screenshot:

Screenshot 1

Even though, the .xml is correctly created and user can download from attachments instead, see screenshot.

Screenshot 2

**Comment by felixvillafranca** [comment]
Hi @misern2 , @HaraldPanten 

IMO works fine¡
The problem is in file [ir_attachment.xml](https://github.com/OCA/bank-payment/blob/13.0/account_payment_order/views/ir_attachment.xml) on account_payment_order.
Changing "store_fname" for "name" in line 17 & 20 solve the problem.

Regards,

**Review by felixvillafranca — COMMENTED** [review]
Functional 🆗

**Comment by ValentinVinagre** [comment]
Hi @misern2 @felixvillafranca @HaraldPanten ,
I fixed the issue  in https://github.com/OCA/bank-payment/pull/700

**Comment by misern2** [comment]
@ValentinVinagre Thanks for the fixing, but in this PR #700  you are also fixing another things and it may take longer to be merged. Anyway the issue detected it's not  related to this module so I think that we should not block it. What do you think ? @HaraldPanten @felixvillafranca

**Review by HaraldPanten — APPROVED** [review]
> @ValentinVinagre Thanks for the fixing, but in this PR #700 you are also fixing another things and it may take longer to be merged. Anyway the issue detected it's not related to this module so I think that we should not block it. What do you think ? @HaraldPanten @felixvillafranca

I agree @misern2 . Functional review 👍

**Comment by ValentinVinagre** [comment]
Hi, the fix https://github.com/OCA/bank-payment/pull/700 is merged.

**Comment by misern2** [comment]
Thanks @ValentinVinagre . @pedrobaeza  I think that this is ready to merge.

**Comment by HaraldPanten** [comment]
Hi @ValentinVinagre @felixvillafranca @sergio-teruel @pedrobaeza ,

Could you have a look at this PR? IMO it's close to be ready to merge. Thanks.

**Review by AaronHForgeFlow — APPROVED** [review]
It works as expected :+1:

**Review by ValentinVinagre — APPROVED** [review]
LTGM 👍

**Pull request merged**
