### PR TITLE
[17.0][MIG] account_payment_order_notification: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 159500
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/bank-payment/issues/1173

### CODE REVIEW

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — COMMENTED** [review]
LGTM, code review and tested in runboad

**Review by BernatObrador — APPROVED** [review]
LGTM, tested in runboat and code review

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_payment_order_notification
/ocabot merge nobump

**Pull request merged**
