### PR TITLE
[IMP] account_payment_sale: Add payment mode in invoicing grouping criteria

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@alexis-via @jbaudoux

**Review by jbaudoux — APPROVED** [review]
LGTM

**Review by lmignon — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

To be fw-ported it to v17

**Pull request merged**
