### PR TITLE
[14.0][ADD] account_payment_order_tier_validation

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
a very welcomed tier validation module.

**Review by antoniospneto — APPROVED** [review]
Functional and code review 👍🏻

**Comment by marcelsavegnago** [comment]
ping @OCA/banking-maintainers

**Review by douglascstd — CHANGES_REQUESTED** [review]
Funcional tests OK. There are fixes in the User Interface, the issue is those items are duplicated.

Print Screens:
On the request validation, the button: "Request Validation" **(duplicated field)**
image

The status change FROM:Draft TO: Confirmed (situation: without validation) **(duplicated field)**
image

To view the status progress on the "Review"  **(duplicated field)**
image

Validation - **(duplicated field)**
image
image

The other status changes (File Generated / File Uploaded) don't apply the Tier Validation, this is expected.
image

**Comment by marcelsavegnago** [comment]
@douglascstd the interface issue has been resolved

**Review by douglascstd — APPROVED** [review]
[APPROVED] Functional test

image

image

**Review by antoniospneto — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/banking-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/banking-maintainers

**Comment by rvalyi** [comment]
I rarely use my merge rights in this repo, but I'm quite confident this e a great and clean module, so I'm merging. I hope it's okay.

**Comment by pedrobaeza** [comment]
Bad timing for using such privilege... GH actions is failing right now: https://www.githubstatus.com/

**Comment by rvalyi** [comment]
> Bad timing for using such privilege... GH actions is failing right now: https://www.githubstatus.com/

too bad. I cancelled the merge job.

**Comment by pedrobaeza** [comment]
@rvalyi it seems everything has returned to normal state in GitHub.

**Pull request merged**
