### PR TITLE
[16.0][MIG] account_payment_order_transfer_journal

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@pedrobaeza 
can you remove the 'stale' from this PR or will it be removed automatically since there is again activity now ?

**Comment by pedrobaeza** [comment]
/ocabot migration account_payment_order_transfer_journal

Removed.

**Review by ghost — CHANGES_REQUESTED** [review]
LGTM

**Comment by alexis-via** [comment]
I support this PR. It's good to have this option in the module account_payment_order.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@pedrobaeza @alexis-via @luc-demeyer Is there anything missing to merge this PR and move forward ? I think it would be great to having it merge before reviewing and moving forward with this PR https://github.com/OCA/bank-payment/pull/1174

**Review by bosd — APPROVED** [review]
LGTM

**Comment by dreispt** [comment]
Superseded by #1243

**Pull request closed without merging**
