### PR TITLE
[13.0][FIX] account_payment_partner: Set correct journal in tests to prevent error

### PR DESCRIPTION
**Pull request by victoralmau**
Set correct journal in tests to prevent error.

Please @pedrobaeza and @joao-p-marques can you review it?

It's need to fix in 14.0 too.

@Tecnativa TT28743

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@victoralmau please check Travis

**Comment by victoralmau** [comment]
Travis fail in `account_payment_order_return`.
Do we make the changes to that addon in this PR or in a new one?

**Comment by pedrobaeza** [comment]
In the same, but as separate commits. If not, we won't be able to merge any.

**Pull request merged**
