### PR TITLE
[MIG] account_banking_sepa_credit_transfer: Migration to 13.0

### PR DESCRIPTION
**Pull request by axelpriem**
Depends on account_banking_pain_base #670 
(and indirectly on account_payment_order #651, account_payment_partner #649 , account_payment_mode)

### CODE REVIEW

**Comment by misern2** [comment]
@axelpriem Please resolve conflicts.

**Comment by axelpriem** [comment]
I solved the conflicts, didn't I?... Can the merge be done please?

**Comment by misern2** [comment]
@axelpriem There's a precommit failure on travis. Can you chek it , please ?

**Comment by HaraldPanten** [comment]
Hi @axelpriem , I see that @pedrobaeza is going to handle https://github.com/OCA/bank-payment/pull/670 . What about this one? Do you have availability to continue with this PR once https://github.com/OCA/bank-payment/pull/670 is merged?

Thanks!

**Comment by HaraldPanten** [comment]
Hi @axelpriem is it OK for you if we manage this PR?

Thanks!

**Comment by axelpriem** [comment]
I don't have the time to handle this in the immediate future, sorry. So if you are able to handle it, that would be great! Thanks so much!

**Comment by HaraldPanten** [comment]
Sure! no problem 👍

**Comment by HaraldPanten** [comment]
Hi @axelpriem you can close this one as well, we're working on it in: https://github.com/OCA/bank-payment/pull/699

Thanks!

**Comment by axelpriem** [comment]
Thanks!

**Pull request closed without merging**
