### PR TITLE
[17.0][FIX] account_payment_order: fix ``TypeError``

### PR DESCRIPTION
**Pull request by SilvioC2C**
Method ``_get_reconciled_invoices_partials()`` returns 2 lists:
- the first one contains triplets defined as (account.partial.reconcile record, amount, account.move.line record)
- the second one contains account.move IDs

Merging the 2 lists and cycling over them with
```
for (_x, _y, payment_move_line) in list1 + list2:
    ...
```
resulted in ``TypeError: cannot unpack non-iterable int object``.

This commit fixes this bug.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe you can add a regression test so this doesn't happen again in another migration (or upstream change)? Being a very low method, the chances to break again are high.

**Comment by SilvioC2C** [comment]
@pedrobaeza alas, I'm on a tight schedule at the moment and I don't have enough functional knowledge to replicate the issue; I'll try to do it asap though

**Comment by pedrobaeza** [comment]
OK, thanks!

**Review by yankinmax — APPROVED** [review]

**Review by vvrossem — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge for now to fix the problem. The test may come later (but please don't forget it):

/ocabot merge patch

**Pull request merged**
