### PR TITLE
[17.0][IMP] account_payment_order: update payment reference on open payment order

### PR DESCRIPTION
**Pull request by luc-demeyer**
This commits adds the possibility to update the payment reference on a payment transaction before generating XML file.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
forward port of https://github.com/OCA/bank-payment/pull/1170

**Comment by pedrobaeza** [comment]
Please put the commit message properly according guidelines:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by pedrobaeza** [comment]
@luc-demeyer can you rebase and forced push for having CI?

**Comment by luc-demeyer** [comment]
@pedrobaeza : rebased

**Review by pedrobaeza — APPROVED** [review]
The same as v16, so merging it:

/ocabot merge minor

**Pull request merged**
