### PR TITLE
Fix mandates tree view in res.partner.bank for better ergonomy

### PR DESCRIPTION
**Pull request by moctarjallo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is it better ergonomy? Please put screenshots of before and after. Isn't this simply to put `col=2` on existing definition?

**Comment by moctarjallo** [comment]
`col=2` wouldn't work.

Here's what it looks like before and after.

Before
After

**Review by pedrobaeza — APPROVED** [review]
It works most of the times with col=2, but your proposal is also good.

**Review by bofiltd — APPROVED** [review]

**Review by bosd — APPROVED** [review]
LGTM

**Pull request merged**
