### PR TITLE
[WIP][ADD] account_cash_discount_stock module

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Did you mean to propose in this repository? Also, the usage in the README seems off "To use this module you can use payment order ".

**Comment by pedrobaeza** [comment]
@sbidoul is this still interesting for you or should we move to later versions?

**Comment by sbidoul** [comment]
This is running in production but we don't plan additional work on 8.0.

**Comment by pedrobaeza** [comment]
Closing as stated in https://github.com/OCA/bank-payment/pull/208#issuecomment-391269605

**Pull request closed without merging**
