### PR TITLE
[ADD] account_payment_order_check

### PR DESCRIPTION
**Pull request by etobella**
This module allows to use Payment order in order to create multiple checks.

It will generate a PDF with all the checks to be used.

Configuration
=============

* Create a Payment Mode dedicated to Check Printing.

* Select the Layout of the Payment mode

Usage
=====

In the menu *Invoicing/Accounting > Payments > Payment Order*, create a new
payment order and select the Payment Mode dedicated to Check printing
that you created during the configuration step.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you check Travis?

**Comment by etobella** [comment]
Travis is red on OCA/11.0 as you can see on https://travis-ci.org/OCA/bank-payment/builds/501124355 it seems not related to this PR.

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1:

**Review by albariera — APPROVED** [review]

**Pull request closed without merging**
