### PR TITLE
[ADD] Added Support for payments in Austria

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
For me this should be in Austrian localization, not here. In the past, a specific German format was introduced here and it's a pain for non German contributors/migrators to know if the compatibility is kept when migrating or doing any change.

**Comment by wpichler** [comment]
Sounds good for me - i will close this an open a new in austria localization

**Comment by wpichler** [comment]
There is no l10n-austria - can you create one ?

**Comment by pedrobaeza** [comment]
Doing soon!

**Comment by wpichler** [comment]
ok - i will close this for now

**Comment by pedrobaeza** [comment]
Everything is set in https://github.com/OCA/l10n-austria!

**Comment by wpichler** [comment]
Thanks

**Pull request closed without merging**
