### PR TITLE
[14.0] account_payment_order: communication required in form view

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks, fast-tracking it for restoring the good behavior:

/ocabot merge minor

**Comment by alexis-via** [comment]
Thanks. I've added in my TODO list to up-port it to v15

**Comment by pedrobaeza** [comment]
I'm not seeing the module migrated nor any PR, so only rescuing the commit history will serve.

**Comment by alexis-via** [comment]
There was a PR to migrate account_payment_order to v15 in Qubiq/bank-payment branch 15.0-mig-account_payment_order, cf https://github.com/QubiQ/bank-payment/tree/15.0-mig-account_payment_order  but I can't find the PR any more... strange !

**Comment by alexis-via** [comment]
OK, I found it: the PR is here: https://github.com/OCA/bank-payment/pull/876
When you search on account_payment_order, you don't find it because they didn't put the underscore in the title of the PR!

**Comment by pedrobaeza** [comment]
Yeah, I see. Written on the PR and title normalized.

**Pull request merged**
