### PR TITLE
[FIX] we also need to rename our table

### PR DESCRIPTION
**Pull request by hbrunn**
fixup for #320

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Yeah, that's something I came up with yesterday. Why the method doesn't rename also the columns?

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking when CIs finish

**Comment by hbrunn** [comment]
thanks for the fast track. I think the reasoning for this being two functions is that the orm doesn't necessarily exist when you call those functions, and only the orm knows reliably what the table backing a model is, that's not persisted somewhere in the database to my knowledge.

**Comment by pedrobaeza** [comment]
Yeah, you're right. I have added a warning in the method docstring as reminder: https://github.com/OCA/openupgradelib/commit/39416d214750a1dbb7ec7f4eb99e0fc1c7cc4d89

**Pull request merged**
