### PR TITLE
[15.0][MIG] account_payment_purchase_stock

### PR DESCRIPTION
**Pull request by leemannd**
- taking over migration done in -> https://github.com/OCA/bank-payment/pull/878
- rebase on 15.0
- removal of the oca test-dependencies

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @OCA/banking-maintainers, a review and maybe a merge are welcome

**Review by cyrilmanuel — APPROVED** [review]
not an expert but LG

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM

**Comment by etobella** [comment]
Can you squash last two commits

**Comment by pedrobaeza** [comment]
As the changes of the last commit won't be ported to upper versions not belonging to the module directory, let's merge this for unblocking it:

/ocabot merge nobump

**Pull request merged**
