### PR TITLE
[8.0] account_banking_payment_export: migrate payment.order total

### PR DESCRIPTION
**Pull request by pedrobaeza**
Solution for the problem with the payment order workflow calculating the store field, started and final solution draft by @hbrunn.

cc @sbidoul

### CODE REVIEW

**Comment by hbrunn** [comment]
great, thanks! :+1:

**Comment by pedrobaeza** [comment]
Can you please check this one to avoid the current error on repo?

**Comment by rafaelbn** [comment]
Thanks! :+1:

**Comment by pedrobaeza** [comment]
OK, I think I can merge as this was started by Holger and there's also my approval on the initial code.

**Pull request merged**
