### PR TITLE
[16.0][FIX] account_payment_mode: error when payment mode

### PR DESCRIPTION
**Pull request by EmilioPascual**
Back-port of the fix introduced in https://github.com/OCA/bank-payment/pull/1312

@moduon MT-5800

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Maybe the test in #1298 can be reused here if it triggers the problem?

**Comment by EmilioPascual** [comment]
> Maybe the test in #1298 can be reused here if it triggers the problem?

I think this PR not fixes problem in https://github.com/OCA/bank-payment/pull/1298

**Review by rafaelbn — APPROVED** [review]
👍🏼 

Thank you! ❤️

**Pull request merged**
