### PR TITLE
[ENH] Add backport of trunk bank statement import modules.

### PR DESCRIPTION
**Pull request by NL66278**
```
- Using idea and patches from Alexis de Lattre.
```

### CODE REVIEW

**Comment by sbidoul** [comment]
@NL66278 thanks! 

Following thread [1], I think we should create another OCA project named OCA/bank-statement-import for these modules. That will help ensuring all concepts (payment, bank statement import, bank statement enrichment and reconcile) are kept as orthogonal as possible.

There was not much feedback on my proposal, except @jgrandguillaume who agreed. Perhaps the time has come.

[1] https://lists.launchpad.net/banking-addons-drivers/msg00120.html

**Comment by sbidoul** [comment]
Then there is the flake8 issue. In this case, I believe we must exclude these modules from flake8/pylint checks as we want them to remain as close as possible to upstream, in order to facilitate maintenance if/when upstream evolves.

**Comment by NL66278** [comment]
Maybe I can flake-correct the modules anyway, as in upstream (odoo trunk/9.0) these are part of odoo/addons, not part of banking.

**Comment by sbidoul** [comment]
@NL66278 if you do the pep8 changes, it will be much more difficult to compare with upstream, and copy upstream changes during the lifetime of 8.0.

**Comment by NL66278** [comment]
@sbidoul
OK, no pep8 changes then.

It is a little bit sad that even with new modules the odoo developers do not seem to do any quality checking, or do not follow any coding standards.

How to remove these modules from the flake8/pylint checks ?

**Comment by pedrobaeza** [comment]
I agree we should split this into a new project for get a cleaner vision of what are new lines with banking (in general) addons. We should push OCA to make the move.

**Comment by sbidoul** [comment]
@pedrobaeza if you agree, would you reply to my email on the banking-addons-drivers mailing list se we can push the OCA board with the implementation of the guidelines?

**Comment by NL66278** [comment]
Personally I do not see any advantage in splitting the banking project in different projects. Most companies will then need to checkout three projects instead of one. And as a developer I think that importing statements, reconciling the statement lines and exporting payments are different functional area's, but they definitely share a lot of data.

**Comment by pedrobaeza** [comment]
@NL66278 It's more a cleaning strategy than an area split decission. Having this new repo for import, we start from scratch and all modules present in it are with the new components, and we can even backporting them to v7, but having in the same repo, user will be confused about what modules to use.

**Comment by NL66278** [comment]
How can the user be confused what modules to use? Those not ready to be used are in **unported** and not installable. The rest can be used. And why would a backport to 7.0 be of any use? The version 7.0 modules are working quite well as is.
Somehow I get the impression that we have some miscommunication. 
Anyhow, I am busy refactoring the bank statement import modules, which amongst many other things means separating the issues of reconciliation and of importing, and putting those in separate modules. If you would like to split (or cleanup) the repositories later, this will certainly help.
In the meantime: is there anything in this pull request that makes possible future moves to split (or cleanup) more difficult? In other words, should this discussion hold up this pull request?

**Comment by NL66278** [comment]
I do not see how to exclude parts of the repository from the flake8 tests. Can this be done? Hpw? Or should we accept that what we put in the OCA banking repositories will differ (in following coding standards) from the standard Odoo modules?

I do not think it is a good idea to accept OCA/banking failing the Travis CI build.

It is a pity OpenERP SA does not follow any coding standards, even for new developments.

**Comment by max3903** [comment]
I need to import a bank statement from the National Bank of Canada in version 8. 

Whatever the solution you come up with, Travis needs to be happy and I don't have any problem installing banking and bank-statement-reconcile.

So let's move forward, please.

**Comment by sbidoul** [comment]
@max3903 I created issue https://github.com/OCA/maintainer-quality-tools/issues/132 to progress with the flake8 ignore topic.

Regarding the new repository, can you provide your view in thread https://lists.launchpad.net/banking-addons-drivers/msg00120.html (which currently has @jgrandguillaume, @pedrobaeza, @alexis-via and myself voting +1 and @NL66278 expressing concerns here). 

If the OCA board considers it's a good idea, someone in the board must proceed with the suggested operations (mainly creating a new repo for bank statement import) so we can move forward.

**Comment by sbidoul** [comment]
@NL66278 two solutions have been proposed https://github.com/OCA/maintainer-quality-tools/issues/132 for the pep8 issue. Putting # noqa at the top of the backported files seems the easiest.

**Comment by bwrsandman** [comment]
If you use `# noqa` please add an explanation why it's there:

``` python
# noqa: This is a backport module from Odoo, OCA has no control over style here
```

Dating it would also be a good idea for when 9.0 diverges enough from 8.0 that they become incompatible as therefore need to fork. At which point `# noqa` should be removed.

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
In order to speed up the number of visible v8 modules of OCA (not spread across a hundred of PRs), I give my :+1: to include this PR in the repository. Later, if we move to an isolated repo, we can move these modules there.

If nobody opposses, tomorrow night I will do the merge to move on, because I have spanish bank statement module waiting for this PR.

**Comment by sbidoul** [comment]
@pedrobaeza let's try to get someone with OCA board superpower to make thing moves. It is the right moment to clarify the banking addons landscape. cc/ @jgrandguillaume

**Comment by sbidoul** [comment]
@NL66278 you can now port this PR to https://github.com/OCA/bank-statement-import. Therefore I'm closing this one.

**Comment by pedrobaeza** [comment]
@NL66278, can you please make the PR to https://github.com/OCA/bank-statement-import?, or if you want, I can do it for you. We need this to continue with our localization.

**Comment by NL66278** [comment]
Hello Pedro,

I am working on it now.

Kind regards,

Ronald

Op 04-12-14 om 14:09 schreef Pedro M. Baeza:

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request closed without merging**
