### PR TITLE
[16.0][MIG] account_banking_pain_base

### PR DESCRIPTION
**Pull request by wpichler**
https://github.com/OCA/bank-payment/issues/964

### CODE REVIEW

**Comment by wpichler** [comment]
This will need these cahnges:
https://github.com/OCA/bank-payment/pull/979/commits/15661a262114480908042d69296ed53100e37929

**Comment by Reyes4711-S73** [comment]
@wpichler You added also the modules banking sepa direct debit and account_banking_mandate.
This modules must be migrated in other PR separeted, so please, remove it.
@pedrobaeza

**Comment by wpichler** [comment]
Rebased and removed the two modules which do not belong to this PR

**Comment by wpichler** [comment]
Is there any way to specify other PR here for the runboat to fetch before running the tests ?

**Comment by Reyes4711-S73** [comment]
@wpichler maybe this is useful for you in this case:
https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by wpichler** [comment]
> @wpichler maybe this is useful for you in this case: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

Thank you - that was exact what i was looking for - works like a charm

**Review by ivantodorovich — APPROVED** [review]

**Review by Reyes4711-S73 — APPROVED** [review]

**Comment by Reyes4711-S73** [comment]
@OCA/banking-maintainers There are some PR depending on this and others, Could you review and merge the maximum as possible?

**Comment by hildickethan** [comment]
[[DEL] Removed modules which do not belong to this PR](https://github.com/OCA/bank-payment/pull/974/commits/62ce153ee760db5dc196c26bfb03275fd2905289)
this commit is unnecessary if you remove the commits of those other modules from the history, which is better since theyre entirely useless here

[[IMP] Precommit updates](https://github.com/OCA/bank-payment/pull/974/commits/6caa35ff59fa11586e8e38901dd565a0bd8adaf5)
this commit should also disappear once the other module commits are gone and squashed into [[IMP] account_banking_pain_base: pre-commit stuff](https://github.com/OCA/bank-payment/pull/974/commits/fd1f82b79a0ac551c12320a2e5ec556bd567aa98)

**Review by hildickethan — APPROVED** [review]
migration itself LGTM, just need the commit cleanup

**Review by AnizR — APPROVED** [review]
Code LGTM. But can you apply the request concerning commits cleanup?

**Comment by astirpe** [comment]
@wpichler module `account_payment_order` was merged into V16. Could you please remove test-requirements.txt and rebase this PR?

**Comment by pedrobaeza** [comment]
A commit squashing and to include this commits is needed: https://github.com/OCA/bank-payment/pull/979/commits/15661a262114480908042d69296ed53100e37929

**Comment by StephaneMangin** [comment]
cc @wpichler You can remove this dependency https://github.com/OCA/bank-payment/pull/972
Superseeded by https://github.com/OCA/bank-payment/pull/1056 and merged.

**Comment by StephaneMangin** [comment]
cc @wpichler A gentle ping to remind ;)

**Comment by StephaneMangin** [comment]
cc @wpichler Do you need help for this PR ? to push forward

**Comment by StephaneMangin** [comment]
cc @wpichler Any update about this PR ?

**Comment by manuelcalerosolis** [comment]
Trying to download this module I get the following error :

fatal: refusing to merge unrelated histories
(ERROR) [10:02:14] git_aggregator.repo  bank-payment   /opt/odoo/custom/src/bank-payment> error calling ('git', 'pull', '--no-edit', '--quiet', '--depth', '100', 'origin', 'refs/pull/974/head')

**Comment by rousseldenis** [comment]
@wpichler

**Comment by pedrobaeza** [comment]
The commit history of this one is totally mangled, with more than 250 commits where there's actually less than a hundred, so I have started the commit history fetching from the scratch. As there's no significant changes on the module itself either, and the migration commit of this one is not correct, I'm totally discarding it in favor of #1087, so closing this one and merging the other for finally unblocking this.

**Pull request closed without merging**
