### PR TITLE
[14.0][FW] account_payment_partner: multiple ports from 13.0

### PR DESCRIPTION
**Pull request by hailangvn**
Port of the following PRs from 13.0 to 14.0:
* #796
* #843

### CODE REVIEW

**Review by TDu — APPROVED** [review]

**Review by sebalix — APPROVED** [review]
LG thank you

**Comment by nilshamerlinck** [comment]
Hi @pedrobaeza looks like the bot was off on that day :) would you mind trying the merge again to see if it was just temporary or if there's something wrong at the repo level?

**Pull request merged**
