### PR TITLE
[14.0][FIX] account_payment_order, fix access to setup bank manual

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by GSLabIt** [comment]
> Steps to reproduce the problem?

Sorry, you are right 😬

Log in as Account Manager (not admin) with extra settings: Payments enabled. 

Go to Account -> Configuration -> Add Bank Account.

Before the pr, access error is raised.

**Comment by GSLabIt** [comment]
@pedrobaeza any chance to review?

**Comment by rousseldenis** [comment]
@GSLabIt This is the current config in account module:

image


You want to say, if you are not member of Account Manager group, but have access to payments, you cannot add a bank account ?

**Comment by GSLabIt** [comment]
> @GSLabIt This is the current config in account module:
> 
> image
> 
> You want to say, if you are not member of Account Manager group, but have access to payments, you cannot add a bank account ?

I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.

**Comment by rousseldenis** [comment]
> I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.

:sweat_smile: Yes, but if you are Account Manager, you have access to it.

**Comment by GSLabIt** [comment]
> > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> 
> 😅 Yes, but if you are Account Manager, you have access to it.

You can be right, but i am not able to add a bank account, it require Admin rights to add it.

**Comment by GSLabIt** [comment]
> > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> 
> 😅 Yes, but if you are Account Manager, you have access to it.

https://user-images.githubusercontent.com/11652845/173369650-9eb76875-8bf3-4d5b-8690-3312c751174c.mov

**Comment by rousseldenis** [comment]
> > > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> > 
> > 
> > sweat_smile Yes, but if you are Account Manager, you have access to it.
> 
>  Registrazione.schermo.2022-06-13.alle.15.53.53.mov

Mmmmh, the access error is on 'res.company' not the wizard...

**Comment by GSLabIt** [comment]
> > > > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> > > 
> > > 
> > > sweat_smile Yes, but if you are Account Manager, you have access to it.
> > 
> > 
> > Registrazione.schermo.2022-06-13.alle.15.53.53.mov
> 
> Mmmmh, the access error is on 'res.company' not the wizard...

Some field in the wizard may have access to res.company, actually this pr solve the issue .. 😬

**Comment by rousseldenis** [comment]
> > > > > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> > > > 
> > > > 
> > > > sweat_smile Yes, but if you are Account Manager, you have access to it.
> > > 
> > > 
> > > Registrazione.schermo.2022-06-13.alle.15.53.53.mov
> > 
> > 
> > Mmmmh, the access error is on 'res.company' not the wizard...
> 
> Some field in the wizard may have access to res.company, actually this pr solve the issue .. grimacing

Yes, I understand. But one question remain : Should the payment group have access to create bank account ???

**Comment by GSLabIt** [comment]
> > > > > > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> > > > > 
> > > > > 
> > > > > sweat_smile Yes, but if you are Account Manager, you have access to it.
> > > > 
> > > > 
> > > > Registrazione.schermo.2022-06-13.alle.15.53.53.mov
> > > 
> > > 
> > > Mmmmh, the access error is on 'res.company' not the wizard...
> > 
> > 
> > Some field in the wizard may have access to res.company, actually this pr solve the issue .. grimacing
> 
> Yes, I understand. But one question remain : Should the payment group have access to create bank account ???

Seems it is by module design: 

https://github.com/OCA/bank-payment/blob/14.0/account_payment_order/security/ir.model.access.csv#L5

**Comment by GSLabIt** [comment]
> > > > > > I'm saying, if u don't have access to wizard as `group_account_payment` you're not able to add a bank account.
> > > > > 
> > > > > 
> > > > > sweat_smile Yes, but if you are Account Manager, you have access to it.
> > > > 
> > > > 
> > > > Registrazione.schermo.2022-06-13.alle.15.53.53.mov
> > > 
> > > 
> > > Mmmmh, the access error is on 'res.company' not the wizard...
> > 
> > 
> > Some field in the wizard may have access to res.company, actually this pr solve the issue .. grimacing
> 
> Yes, I understand. But one question remain : Should the payment group have access to create bank account ???

Seems it is by module design: 

https://github.com/OCA/bank-payment/blob/14.0/account_payment_order/security/ir.model.access.csv#L5

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by francesco-ooops** [comment]
> > Steps to reproduce the problem?
> 
> Sorry, you are right 😬
> 
> Log in as Account Manager (not admin) with extra settings: Payments enabled.
> 
> Go to Account -> Configuration -> Add Bank Account.
> 
> Before the pr, access error is raised.

Tried with this setup the steps described, still getting the Administration/Access Rights dialog

did I miss something?

image

**Comment by francesco-ooops** [comment]
seems like the problem is not related to account_payment_order as it's replicable on odoo 14 and 15 runbot, issue opened: https://github.com/odoo/odoo/issues/94680

@rousseldenis @pedrobaeza do you have any suggestion for a fix to propose in an odoo PR?

**Comment by pedrobaeza** [comment]
Thanks for checking that. It was very weird that this depends on `account_payment_order`. Closing this PR then. I have pinged to some people at Odoo in the issue.

**Pull request closed without merging**
