### PR TITLE
[16.0][FIX]Fixed error on XML creation data in account_banking_sepa_direct_debit.

### PR DESCRIPTION
**Pull request by 10537**
This changes fix a error when the xml is create, you can view more details in this issue: [Issue 1131](https://github.com/OCA/bank-payment/issues/1131)

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This solution is not correct. It's forcing to use the first bank account of the partner, when you have the possibility of choosing another. Your problem probably comes from having incorrectly filled the bank account on your invoice.

**Comment by cesarsc79** [comment]
Pedro:

The bank account is filled correctly on the invoice

**Comment by pedrobaeza** [comment]
And in the payment line?

**Comment by cesarsc79** [comment]
The bank account is filled correctly in the payment line too

**Comment by pedrobaeza** [comment]
Then this line should dump such bank account to the XML file:

https://github.com/OCA/bank-payment/blob/927df0fe880e329abb2b9ca449b2c28831705f4e/account_banking_sepa_direct_debit/models/account_payment_order.py#L251

**Pull request closed without merging**
