### PR TITLE
[16.0][MIG] account_banking_mandate: migration to 16.0

### PR DESCRIPTION
**Pull request by Reyes4711-S73**
Superseed from https://github.com/OCA/bank-payment/pull/1016 due to the fact that the PR was not migrated correctly
I remove the bank_payment_line model and complete the tests correcting some issues

depends https://github.com/OCA/bank-payment/pull/972

### CODE REVIEW

**Comment by AsierAcedo** [comment]
Hello there is an older PR #973

**Comment by Reyes4711-S73** [comment]
@AsierAcedo This pass all tests and the older PR doesn't pass any test.

**Comment by pedrobaeza** [comment]
/ocabot migration account_banking_mandate

Please squash administrative commits as stated in the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0. For example, last three commits before migration that belongs to the same translator.

**Comment by Reyes4711-S73** [comment]
@pedrobaeza Squash done

**Comment by pedrobaeza** [comment]
I still see administrative commits. Examples:

Selección_079

**Comment by Reyes4711-S73** [comment]
@pedrobaeza Squashed more commits.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
