### PR TITLE
[16.0][MIG] account_banking_sepa_direct_debit: Migration to 16.0

### PR DESCRIPTION
**Pull request by Reyes4711-S73**
superseed from https://github.com/OCA/bank-payment/pull/1019
Standard migration to 16.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should include the part of #1031 that corresponds to this.

**Comment by Reyes4711-S73** [comment]
@pedrobaeza Added #1031

**Comment by AntoniRomera** [comment]
Any progress?

**Comment by AntoniRomera** [comment]
### Functional Review
It seems correct, I have created a debit order and I have tried to generate the file, it seems to have the XML schema, the only thing missing would be a warning that the journal does not have a bank account configured or let you set the bank account by hand if it does not.

**Review by AntoniRomera — APPROVED** [review]

**Comment by manuelcalerosolis** [comment]
@Reyes4711-S73 

You may need to update the [test-requirements.txt](https://github.com/OCA/bank-payment/pull/1029/commits/f5d6835c2af47307a38c32f37a65990ad5a4982c), this dependency has already been merged.

**Comment by Reyes4711-S73** [comment]
@manuelcalerosolis done

**Review by FernandoRomera — APPROVED** [review]

**Review by manuelcalerosolis — APPROVED** [review]

**Review by enriquemartin — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@pedrobaeza can you merge?

**Comment by Reyes4711-S73** [comment]
@AntoniRomera First must be merged this PR https://github.com/OCA/bank-payment/pull/974

**Comment by pedrobaeza** [comment]
/ocabot migration account_banking_sepa_direct_debit

Please rebase and solve conflicts, and include #1066 

You should squash some migration commits as well, and reorder the existing commits.

**Comment by Reyes4711-S73** [comment]
@pedrobaeza Done

**Comment by pedrobaeza** [comment]
Thanks

/ocabot merge nobump

**Pull request merged**
