### PR TITLE
[FIX] account_banking_sepa_direct_debit: UserError instead of Warning

### PR DESCRIPTION
**Pull request by willer-mo**
Raise UserError instead of Warning

Before:
image
After:
image

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Review by Abranes — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Is this happening in upper versions?

**Comment by willer-mo** [comment]
> Is this happening in upper versions?

It is, only in version 11.0

**Comment by pedrobaeza** [comment]
OK, thanks for confirming.

**Comment by pedrobaeza** [comment]
Please do the PR for 11.0

**Pull request merged**
