### PR TITLE
[10.0][MIG] account_payment_purchase

### PR DESCRIPTION
**Pull request by GillesTephaneMeyomesse**

### CODE REVIEW

**Comment by alexis-via** [comment]
FYI, when I ported OCA/bank-payment to v9/v10, I decided not to port this module because I feel it was against the new philosophy of supplier invoice creation in Odoo. Since v9, the supplier invoices are not created from PO but they are created empty (so payment mode is taken from res.partner) and then the lines are pulled from selected POs.

**Comment by pedrobaeza** [comment]
Well, I think it's needed, as you can specify at purchase order level the payment mode. I know that it can be conflictive if you add 2 purchase orders with different payment mode, but maybe this can be handled some way...

**Comment by alexis-via** [comment]
FYI, I made a test on v10:
- partner1 with payment term PTA and fiscal position FPA
- create a PO for partner1 and change the payment term to PTB and change the fiscal position to FPB
- validate PO
- receive products
- create a vendor bill (either from the PO or from the Accounting menu and pull the PO): on the vendor bill, you have payment term = PTA and fiscal position = FPA.

So it confirms my feeling.

**Comment by pedrobaeza** [comment]
Please use the same approach of v9 migration in https://github.com/OCA/bank-payment/pull/355 which handles rough edges like the one commented by @alexis-via

**Comment by pedrobaeza** [comment]
Any news with this?

**Comment by GillesTephaneMeyomesse** [comment]
I have not had much time I will now work on it

**Comment by pedrobaeza** [comment]
@GillesTephaneMeyomesse any news about this?

**Comment by Jortolsa-S73** [comment]
@GillesTephaneMeyomesse, we can do the changes requested by @pedrobaeza, it is OK for you?

**Comment by hbrunn** [comment]
@Jortolsa no need to ask, just go ahead, take commits here, push them to a new branch, add your commits and submit a new PR, then we'll deprecate this one as it seems nothing is going to happen here any more.

**Comment by hbrunn** [comment]
PS: when doing so, please follow the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0 for getting commits from the 9 branch

**Comment by pedrobaeza** [comment]
Superseeded by #492

**Pull request closed without merging**
