### PR TITLE
[15.0][MIG]account_payment_sale

### PR DESCRIPTION
**Pull request by manuelregidor**
supersedes https://github.com/OCA/bank-payment/pull/880

### CODE REVIEW

**Comment by manuelregidor** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
@rafaelbn Could you review this PR? It's a simple one. THX.

**Review by HaraldPanten — APPROVED** [review]
Functional review.

**Comment by HaraldPanten** [comment]
I'll do fast-tracking as it was validated by several experienced users here --> https://github.com/OCA/bank-payment/pull/880

**Pull request merged**
