### PR TITLE
7.0 fix translation link partner nl

### PR DESCRIPTION
**Pull request by ghost**
In Link partner form view, form string is not translated. so here is a fix for that for NL lang.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Is the change to the po file the result of a fresh export after the change in the code, or is it added manually?

**Comment by yvaucher** [comment]
@bwrsandman I see this [1] should resolve such issue but is only available on OCB any opinion on accepting such PR ?

[1]https://code.launchpad.net/~savoirfairelinux-openerp/openobject-server/7.0_mail_thread_translate_bug1262000/+merge/208812

**Comment by pedrobaeza** [comment]
Change should be put on pot file also.

**Comment by yvaucher** [comment]
agreed with @pedrobaeza  > need fixing

**Comment by bwrsandman** [comment]
> https://code.launchpad.net/~savoirfairelinux-openerp/openobject-server/7.0_mail_thread_translate_bug1262000/+merge/208812

@yvaucher That was also merged in Odoo

**Comment by yvaucher** [comment]
@bwrsandman thx for the update

so we just need the change in pot file here

**Comment by StefanRijnhart** [comment]
@yvaucher I don't understand. The server fix referred to above is applied here: https://code.launchpad.net/~savoirfairelinux-openerp/openobject-addons/7.0_mail_thread_translate_bug1262000/+merge/199374. In this code, you can see that the model's _description is wrapped in a gettext call _(). Doesn't that mean that we need both changes and the current PR is good as it is?

**Comment by pedrobaeza** [comment]
As this one hasn't been answered for a long time, I close.

**Pull request closed without merging**
