### PR TITLE
[16.0] [MIG] account_payment_mode

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
https://github.com/OCA/bank-payment/issues/964

### CODE REVIEW

**Review by baimont — APPROVED** [review]

**Comment by rafaelbn** [comment]
Thank you @ThomasBinsfeld ! I cannot test it 😢 runboat is not ⛵ 

imagen

**Comment by adrienpeiffer** [comment]
Just reset the build. Let's wait.

**Comment by adrienpeiffer** [comment]
Oh @rafaelbn If you want to test it. Runboat is ready !

**Review by rafaelbn — COMMENTED** [review]
Tested in runbot 👍

imagen


I forgot that now repo is empy! 😄 I'm use to have all 🙏

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍

**Comment by Gelo-fl** [comment]
Hi @dreispt,

This module is merged, however the translations are locked:
[bank-payment-16.0-account_payment_mode](https://translation.odoo-community.org/projects/bank-payment-16-0/bank-payment-16-0-account_payment_mode/)

Can I know why?

Thanks in advance,

**Comment by pedrobaeza** [comment]
Unlocked.

**Pull request merged**
