### PR TITLE
[IMP] sepa: make it easier to extend structured communication types

### PR DESCRIPTION
**Pull request by sbidoul**
Implement the usual trick to make selection field extensible

### CODE REVIEW

**Comment by pedrobaeza** [comment]
With new API, we have now several methods for extending selections:
- Enclose in quotes the method name, and it will be evaluated at execution time, being the same as your lambda method.
- Use _extend_selection_ attribute to add values.

I recommend you to make the change enclosing method in quotes, or don't do any change, and extend selection in derived modules the other way.

**Comment by sbidoul** [comment]
Thanks @pedrobaeza. I implemented your first suggestion.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by sbidoul** [comment]
Is this one good for merging?

**Comment by pedrobaeza** [comment]
Yeah, I think so.

**Pull request merged**
