### PR TITLE
[13.0][IMP]account_payment_order: Add Bank Payment Lines report

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
@ForgeFlow
Add Bank Payment Lines report.

### CODE REVIEW

**Comment by GuillemCForgeFlow** [comment]
@sbidoul could you check this, please? :smile:

**Comment by GuillemCForgeFlow** [comment]
@alexis-via @pedrobaeza @adrienpeiffer @StefanRijnhart @lmignon If any of you have a little time to check this improvement I would really appreciate it! :smile:

**Review by lmignon — APPROVED** [review]
LGTM (Code review only)

**Review by mariadforgeflow — APPROVED** [review]
LGTM!:)

**Comment by GuillemCForgeFlow** [comment]
@HaraldPanten could you merge this, please? :smile:

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Comment by HaraldPanten** [comment]
@GuillemCForgeFlow could you do the same for V14, please?

**Pull request merged**
