### PR TITLE
[12.0][NEW] Account Payment Repair

### PR DESCRIPTION
**Pull request by mileo**
- Add a field payment_mode_id on repair orders;
- Onchange from res.partner customer_payment_mode_id;
- Copy it to the invoice.

cc: @gabrielcardoso21 @marcelsavegnago

### CODE REVIEW

**Comment by mileo** [comment]
Not related but, repair payment term https://github.com/OCA/manufacture/pull/624

**Comment by gabrielcardoso21** [comment]
@mileo this field shoud also go to the report of the repair quotation.

**Comment by mileo** [comment]
> @mileo this field shoud also go to the report of the repair quotation.

Done

**Review by marcelsavegnago — APPROVED** [review]
LGTM. Tested on the runbot

**Review by gabrielcardoso21 — APPROVED** [review]
We can't forget to create translations for the report terms later.

**Comment by mileo** [comment]
@OCA/banking-maintainers Could anyone review?

**Pull request merged**
