### PR TITLE
fix for Paid more does not set invoice to paid status #52

### LINKED ISSUE #52: [v7] Paid more does not set invoice to paid status
I have invoice of the amount of 850. On bank statement i receive a payment of 1000. Now when i confirm the bankstatement line, the invoice does not get the paid status. On the invoice is registered a paymnet of 1000. This is not correct.

The invoice should be reconcilled with the payment and the diff (150) should stay open by default on the debtors account. It should be the same as using the pay botton on the invoice.

### PR DESCRIPTION
**Pull request by ghost**
Resolve #52

### CODE REVIEW

**Comment by gurneyalex** [comment]
can you please add an automated test for this bug fix?

**Comment by StefanRijnhart** [comment]
Agree with @gurneyalex, it should be easy to add a new test to account_banking_tests based on what's there already (which tests payment orders, not single invoices).

**Comment by StefanRijnhart** [comment]
That and the flake8 errors in the Travis run.

**Comment by ghost** [comment]
This is not a proper Fix So I am closing this one

**Pull request closed without merging**
