### PR TITLE
Fixes #47 crash in account_payment_purchase

### LINKED ISSUE #47: Crash in account_payment_purchase
When you create an invoice from an incoming products on v7 with account_payment_purchase:

  File "/home/erp_super/erp/prod/src/addons/stock/stock.py", line 1153, in action_invoice_create
    invoice_vals = self._prepare_invoice(cr, uid, picking, partner, inv_type, journal_id, context=context)
  File "/home/erp_super/erp/prod/src/banking/account_payment_sale_stock/model/stock.py", line 34, in _prepare_invoice
    cr, uid, picking, partner, inv_type, journal_id, context=context)
  File "/home/erp_super/erp/prod/src/banking/account_payment_purchase/model/stock.py", line 38, in _prepare_invoice
    picking.purchase_id.supplier_partner_bank.id or False,
  File "/home/erp_super/erp/prod/src/server/openerp/osv/orm.py", line 504, in __getattr__
    raise AttributeError(e)
AttributeError: "Field 'supplier_partner_bank' does not exist in object 'browse_record(purchase.order, 774)'"

It seems that, when we decided to change to datamodel of the account_payment_\* modules, the file account_payment_purchase/model/stock.py was not changed !!! I'll do a PR to fix this.

### PR DESCRIPTION
**Pull request by alexis-via**
That's a fix in my own code !

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1: 

@pedrobaeza do you track these changes to forward-port to your 8.0 branch?

**Comment by bwrsandman** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Yeah, it's not an issue in my case, as I rewrite it to new API: https://github.com/pedrobaeza/banking/blob/8.0-sepa-migration/account_payment_purchase/models/stock_picking.py#L35

**Pull request merged**
