### PR TITLE
[15.0][MIG] account_payment_order

### PR DESCRIPTION
**Pull request by misern2**
Standard Migration
~~Depends #873~~

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There are new commits in 14.0 branch that should be rescued, and please remember to normalize the PR title to help to find it with searches of the module name.

**Comment by alexis-via** [comment]
Now that the underlying modules are merged, a rebase should make Travis happy.

**Comment by MiquelRForgeFlow** [comment]
Please, cherry pick af433396ffef8e0bd6dce23fab8b08cb0a0ff5b3

**Comment by misern2** [comment]
Added requested cherry-picks. Ready to review!.
Thanks!.
@MiquelRForgeFlow @alexis-via @pedrobaeza

**Review by MiquelRForgeFlow — APPROVED** [review]
code LGTM

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM 👍.

@pedrobaeza go?

**Comment by HaraldPanten** [comment]
I'll merge this one if it's OK for you @alexis-via @pedrobaeza

**Comment by pedrobaeza** [comment]
I haven't reviewed, but if it's OK for you, go ahead

**Pull request merged**
