### PR TITLE
[MIG] account_banking_pain_base: Migration to 13.0

### PR DESCRIPTION
**Pull request by axelpriem**
Depends on account_payment_order #651 
(and indirectly on account_payment_partner #649 , account_payment_mode)

### CODE REVIEW

**Comment by Tardo** [comment]
Please, resolve conflicts.

**Review by HaraldPanten — APPROVED** [review]
I tried this module in local environment and looks good 👍 . Even though, you should check conflicts @axelpriem  Thanks!

**Comment by pedrobaeza** [comment]
@axelpriem please never use GitHub conflict resolution tool, as this messes up commit history. Please undo and perform a proper rebase.

**Comment by axelpriem** [comment]
> @axelpriem please never use GitHub conflict resolution tool, as this messes up commit history. Please undo and perform a proper rebase.

Sorry, I didn't know that. We have a similar problem with gitlab, but I didn't know github had the same issues...
I have corrected it, can you check please?

**Comment by ValentinVinagre** [comment]
Hi @axelpriem ,
I can't see the module 'account_banking_pain_base' in the changes, can you check that?
Is it possible that something has gone wrong with the conflict resolution?

**Comment by axelpriem** [comment]
> Hi @axelpriem ,
> I can't see the module 'account_banking_pain_base' in the changes, can you check that?
> Is it possible that something has gone wrong with the conflict resolution?

You're absolutely right, I forgot something :-).
I rebased my branch to 13.0 yesterday, but forgot to include the new changes. I have now added them to my branch. But I'm still getting a merge conflict on the ".isort.cfg" file. I don't understand. I have rebased my branch to 13.0, why am I still getting this?...

**Comment by ValentinVinagre** [comment]
I see that you are uploading several modules, not only 'Account_banking_pain_base'.
Is it correct? Usually one PR is only for changing one module.

**Comment by HaraldPanten** [comment]
Hi @axelpriem ,

https://github.com/OCA/bank-payment/pull/651 has been merged. Could you solve conflicts?

Thanks!

**Comment by HaraldPanten** [comment]
Hi @axelpriem , please check Travis. This PR almost finished 💪 !

**Comment by axelpriem** [comment]
> Hi @axelpriem , please check Travis. This PR almost finished  !

I have run pre-commit locally, and commited the changes this made to my files, nothing else. Now Travis is giving other errors in the tests!... How do I solve this?! I don't understand.

**Comment by ValentinVinagre** [comment]
Hi @axelpriem ,
travis crashes because 'unidecode' library is not installed in travis.yml, you need to add  '- pip install unidecode ' in '.travis.yml' file like in v.12.

https://github.com/OCA/bank-payment/blob/979261ce0f15cde89344a7d4de4c06a2c629246c/.travis.yml#L29

**Comment by pedrobaeza** [comment]
Better to add it to requirements.txt file in root than to .travis.yml.

**Comment by ValentinVinagre** [comment]
Hi @axelpriem ,
like this example:

https://github.com/OCA/l10n-spain/blob/8af684d5ecc7d3425a97bf8bbe93271efc838969/requirements.txt#L1

Thanks @pedrobaeza

**Comment by axelpriem** [comment]
> Hi @axelpriem ,
> like this example:
> 
> https://github.com/OCA/l10n-spain/blob/8af684d5ecc7d3425a97bf8bbe93271efc838969/requirements.txt#L1
> 
> Thanks @pedrobaeza

Thanks for the help! Everything seems OK now, all checks have passed! :-)

**Comment by ValentinVinagre** [comment]
Hi @axelpriem ,
can you squash commits? 
Thanks,

**Comment by pedrobaeza** [comment]
I'm seeing that you haven't followed the migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0) and isolate the auto-formatting stuff in one commit, so the migration commit is really dirty. Do you want me to supersed this? This is what you can do for fixing it yourself:

- Save current module folder with all migrated.
- Go back to the black, isort commit.
- Rebase
- Run pre-commit again with latest definition and commit amending existing commit.
- Delete module folder and copy back your folder backup.
- Commit the existing diff.

**Comment by axelpriem** [comment]
> I'm seeing that you haven't followed the migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0) and isolate the auto-formatting stuff in one commit, so the migration commit is really dirty. Do you want me to supersed this? This is what you can do for fixing it yourself:
> 
> * Save current module folder with all migrated.
> * Go back to the black, isort commit.
> * Rebase
> * Run pre-commit again with latest definition and commit amending existing commit.
> * Delete module folder and copy back your folder backup.
> * Commit the existing diff.

I had followed the migration guide at the start, but lost track of it with all the extra work that I had to do for this pull request, sorry. Is there any way you guys can handle this? I can do it, but not for a couple of days probably. The problem is that I'm spending a lot of time on this pull request, and for my employer this is non-billable work. And with the corona situation, I have to give priority to billable work right now, sorry. If you cannot do it, I will pick this up later.

**Comment by pedrobaeza** [comment]
OK, for all of us the situation is the same and this is more or less voluntary effort, although your employer must support open source this way, but no worries, I will take over the PR and complete what I'm saying respecting your authorship for finishing this. Thanks for all your efforts.

**Comment by axelpriem** [comment]
> OK, for all of us the situation is the same and this is more or less voluntary effort, although your employer must support open source this way, but no worries, I will take over the PR and complete what I'm saying respecting your authorship for finishing this. Thanks for all your efforts.

Thanks so much for understanding Pedro. My employer certainly supports open source, and normally this would not be an issue. It's a difficult time for everyone indeed! 
This was also my first real PR to OCA, so I hope the next one will be smoother. I'm still learning the process :-)

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza , is it OK for you if we manage this PR? we can do that in the next few days. 👍 

We can do https://github.com/OCA/bank-payment/pull/671 as well.

Thx!

**Comment by pedrobaeza** [comment]
@HaraldPanten as you prefer. I'm a bit overloaded and not able to do it right now.

**Comment by HaraldPanten** [comment]
It's OK, Pedro.

We'll handle this one and https://github.com/OCA/bank-payment/pull/671

**Comment by HaraldPanten** [comment]
Hi @axelpriem , you can close this PR. It's been superseded by https://github.com/OCA/bank-payment/pull/698 . Thanks for your effort

**Comment by axelpriem** [comment]
> Hi @axelpriem , you can close this PR. It's been superseded by #698 . Thanks for your effort

Thank you so much! I will close it now :-)

**Pull request closed without merging**
