### PR TITLE
[MIG] account_invoice_select_for_payment: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**
Hello,

This module has been migrated from this pending MR: https://github.com/OCA/bank-payment/pull/716

Thanks

### CODE REVIEW

**Review by TDu — APPROVED** [review]
LG, thank you

**Comment by TDu** [comment]
Actually it seems that the module in 13.0 has been changed since the migration, could you check ?

**Comment by hailangvn** [comment]
> Actually it seems that the module in 13.0 has been changed since the migration, could you check ?

Thanks TDu for your review. We updated PR with 2 applicable commits. Please help to review again. Thank you in advance.

**Comment by TDu** [comment]
The main commit is still does not look the same than the 13.0 version commit https://github.com/OCA/bank-payment/commit/2b3fe95f18bf3da234fe83fd9b91c02826b1818c#diff-bf45ec33fc02aa24c3431eb4c9ca15426896edd9b88c7127b5a556d6728c447e

@hailangvn Could you check again

**Comment by hailangvn** [comment]
Thanks @TDu for the specific commit. This PR has been updated accordingly.

**Review by TDu — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
