### PR TITLE
[9.0] add german translations to (all) modules

### PR DESCRIPTION
**Pull request by rschnapka**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why doing this on 9.0 branch that is not migrated?

**Comment by rschnapka** [comment]
maybe to give a head start, in case the changes are minor and not language or interface specific? Otherwise yes it's a good question...

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by pedrobaeza** [comment]
This doesn't make sense now, as all the modules have been heavily reworked on https://github.com/OCA/bank-payment/pull/270, so I close it and when merged, it will be available to translate through Transifex.

**Pull request closed without merging**
