### PR TITLE
[16.0][MIG] account_payment_order_return

### PR DESCRIPTION
**Pull request by almumu**
Migration to 16.0

### CODE REVIEW

**Review by yvaucher — APPROVED** [review]
LGTM

Thanks for your contribution @almumu 

About the README, it is automatically constructed, you should add yourself to `account_payment_order_return/readme/CONTRIBUTORS.rst` or next time the README is generated your name will be lost.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
