### PR TITLE
[FIX] Added binding for report account_payment_order

### PR DESCRIPTION
**Pull request by daerio**
Hi, I'm new to contributing to OCA code. I hope this is correct. It seems like this was just missing from the module.

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Thanks for the contribution. It's correct, but 3 things:

- Don't bump version in the manifest. It will be done automatically by the bot.
- Rephrase commit message to follow guidelines: `[FIX] account_payment_order: Bind report to model`
- Did you sign the CLA?

**Review by pedrobaeza — APPROVED** [review]

**Comment by daerio** [comment]
Hi, thanks. 
I updated the commit according to point 1 & 2. About the CLA. I think my employer Vertel AB has signed one earlier. Is there a way to check?

**Comment by pedrobaeza** [comment]
OK, CLA checked. Thanks again.

**Review by dreispt — APPROVED** [review]

**Pull request merged**
