### PR TITLE
[16.0][FIX] account_payment_mode: increase note field size

### PR DESCRIPTION
**Pull request by pausanchezqubiq**
Increase note field size using a colspan

### CODE REVIEW

**Review by chusamo — APPROVED** [review]
Technical Review

**Review by chusamo — APPROVED** [review]
Technical Review

**Review by JanQubiQ — APPROVED** [review]
LGTM!

**Review by ao-landoo — APPROVED** [review]
Functional and technical approval. Looks good, thanks!

**Pull request closed without merging**
