### PR TITLE
[16.0][MIG] account_banking_sepa_credit_transfer: Migration to 16.0

### PR DESCRIPTION
**Pull request by dzungtran89**
#964 

Depends:
- #974

### CODE REVIEW

**Comment by StephaneMangin** [comment]
cc @dzungtran89  You can remove this dependency https://github.com/OCA/bank-payment/pull/972
Superseeded by https://github.com/OCA/bank-payment/pull/1056 and merged.

**Comment by dzungtran89** [comment]
Hi @StephaneMangin , the PR has been updated

**Comment by StephaneMangin** [comment]
You are missing dependencies 

For the PR dependency, please take in account this comment https://github.com/OCA/edi/pull/724#issuecomment-1461765822

**Comment by pedrobaeza** [comment]
There's a wiki entry for it: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by dzungtran89** [comment]
(checking the failed test case)

**Comment by dzungtran89** [comment]
- The failed tests can be fixed by this PR https://github.com/OCA/bank-payment/pull/1068

**Comment by pedrobaeza** [comment]
/ocabot migration account_banking_sepa_credit_transfer

Please rebase and remove the temporary commit.

**Comment by pedrobaeza** [comment]
And please include #1084

**Pull request merged**
