### PR TITLE
[11.0] expand pain support

### PR DESCRIPTION
**Pull request by sbidoul**
Forward port of #502

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please check Travis status?

**Comment by sbidoul** [comment]
Green thanks to @BT-tpiric ! So merging as this is otherwise a forward port of something reviewed in 10.

**Comment by pedrobaeza** [comment]
But this is very dirty in commits with even a revert...

**Comment by sbidoul** [comment]
Fix backported to 10.0 at ed718a26a6ea5e92f6fec5f4f71fca479b6bb04c

**Comment by sbidoul** [comment]
@pedrobaeza gah, I forgot that revert, looking into it.

**Pull request merged**
