### PR TITLE
[16.0][MIG] account_payment_order_notification: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT43211

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @victoralmau @pedrobaeza

**Review by pedrobaeza — COMMENTED** [review]
Please retranslate to Spanish the needed content.

**Comment by Yadier-Tecnativa** [comment]
> Please retranslate to Spanish the needed content.

can you review it? @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
