### PR TITLE
[IMP] account_banking_mandate: Add report SEPA mandate.

### PR DESCRIPTION
**Pull request by sergio-teruel**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Sergio, you can inherit from report.minimal_layout to get a report without header and footer.

**Comment by sergio-teruel** [comment]
Sorry, I have tried to do it with minimal layout but this layout don't work...

**Comment by rlizana** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Checking on runbot, the report is fixed and there's no more full header, so :+1: and I merge.

Thanks for the work.

**Pull request merged**
