### PR TITLE
[RFR] decorate overridable methods in wizard as api.multi

### PR DESCRIPTION
**Pull request by hbrunn**
this way, those functions can react on fields they put into the wizard

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why change that methods? They are not called with ids argument

**Comment by hbrunn** [comment]
@pedrobaeza they are called in `search_entries`, which is `api.multi` itself. So just changing the decorator gives you the ids for free when calling them.

And why do this? I'm now working on allowing my users to select  some journal or analytic account in the wizard, so that they don't have to unset the populate checkbox and filter for the journal/account in question by hand. And with this refactoring, that's a lot more convenient to program.

**Comment by pedrobaeza** [comment]
OK, :+1: 

Please check https://github.com/OCA/bank-payment/pull/169 that improves the pre-selection dialog in the same way as you want, but with partners and general accounts

**Comment by guewen** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Pull request merged**
