### PR TITLE
[15.0][MIG] account_payment_purchase

### PR DESCRIPTION
**Pull request by airlessproject**
Original PR:

https://github.com/OCA/bank-payment/pull/877

Added 3 fixes:
https://github.com/airlessproject/bank-payment/commit/0f12d353507fe9413dfa5558ba706c021b77927e 
(as suggested by https://github.com/MiquelRForgeFlow)

https://github.com/airlessproject/bank-payment/commit/03ca6d0f7dd54892f06a475da09054bbce68b7bf
(fix for unit test)
https://github.com/airlessproject/bank-payment/commit/770e02cad14428cf965d7961192eaf034a32d921
(fix for unit test)

### CODE REVIEW

**Comment by Shide** [comment]
@airlessproject Can you check failed tests please?

**Comment by airlessproject** [comment]
> @airlessproject Can you check failed tests please?

the errors are in other module (account_payment_order)
Module account_payment_purchase which is migrated in this PR doesn't have any errors

Should I try to fix the errors in account_payment_order in this PR?

**Comment by Shide** [comment]
> > @airlessproject Can you check failed tests please?
> 
> the errors are in other module (account_payment_order) Module account_payment_purchase which is migrated in this PR doesn't have any errors
> 
> Should I try to fix the errors in account_payment_order in this PR?

@airlessproject Put the tests in post_install:
https://github.com/OCA/bank-payment/runs/6524133862?check_suite_focus=true#step:8:139

**Comment by airlessproject** [comment]
@Shide Now the tests are failing in 2 assertions. It seems that the account_payment_order module indeed has some issues in the unit tests.

However the tests in account_payment_purchase which is migrated in this PR again don't have any errors.
Please let me know what can we do next.

Thanks!

**Review by ghost — APPROVED** [review]

**Comment by ao-landoo** [comment]
Could you rebase and run tests again?

**Comment by aisopuro** [comment]
@ao-landoo, @airlessproject originally did this for one of my projects, and they've since moved on to other projects. I've opened the new PR #952 which is rebased and passing.

@gelo-landoo may also want to re-approve that one.

Sorry for the messiness.

**Comment by pedrobaeza** [comment]
Superseded by #952

**Pull request closed without merging**
