### PR TITLE
[FIX] bank_statement_instant_voucher: Problems in views and some other enhancements

### PR DESCRIPTION
**Pull request by pedrobaeza**
Added POT file also

### CODE REVIEW

**Comment by pedrobaeza** [comment]
With this, Travis now must be green.

**Comment by pedrobaeza** [comment]
I have to fix another issue, but now all it's OK.

**Comment by StefanRijnhart** [comment]
LGTM, thanks!

**Comment by StefanRijnhart** [comment]
:+1:, that is

**Comment by CSester** [comment]
All changes are legitimes. Nice green Travis.

:+1:

**Pull request merged**
