### PR TITLE
[ADD] module account_invoice_bank_selection

### PR DESCRIPTION
**Pull request by yvaucher**
To restore the visibility of field partner_bank_id on customer invoice

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@yvaucher, is this one abandoned?

**Comment by yvaucher** [comment]
Made lint fixes

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
This module might become useless as new module account_payment_partner will do the same:

https://github.com/akretion/banking/blob/9-sorrento-code-sprint/account_payment_partner/views/account_invoice_view.xml#L34

I'll close this

**Comment by yvaucher** [comment]
Hum not sure if we want to close it as we could need to have it for customer invoices without willing to install payment modules.

**Pull request closed without merging**
