### PR TITLE
[IMP] account_payment_order: Select first partner bank

### PR DESCRIPTION
**Pull request by carlosdauden**
As in this version partner banks have sequence, we automatically select the one with the highest priority

@Tecnativa TT19344

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by Tardo — APPROVED** [review]
LGTM :+1:

**Review by rafaelbn — APPROVED** [review]
:+1: +1

**Comment by rafaelbn** [comment]
I would say this is a FIX :-)

**Pull request merged**
