### PR TITLE
[FIX] After removing module account_iban_preserve_domestic...

### PR DESCRIPTION
**Pull request by NL66278**
[FIX] After removing module account_iban_preserve_domestic, also remove  
  all other modules dependant on this one, or other references to domestic account number.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for inspecting all the code.

:+1:

**Comment by NL66278** [comment]
@pedrobaeza Hello Pedro, actually Stefan RIjnhart did the code inspection, i Just prepared the new pull request.

**Comment by pedrobaeza** [comment]
Well, thank you both! :smile:

**Comment by StefanRijnhart** [comment]
Thanks for the follow up! I think we can remove loading BeautifulSoup in .travis.yml as well now.

**Comment by NL66278** [comment]
I removed beautifulsoup from the .travis.yml file. How can I change the label on this pull request?

**Comment by NL66278** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hello Sandy,

Thanks for willing to help out. However I tried the EDIT button
before, and now again, but I can't find any option to edit the LABEL.
If I click on the label I am transferred to a view on all the pull
requests with the same label.

I must admit I often find the user interface of Github bewildering. I
could not find anything on google as well (perhaps because 'label' is
not a very differentiating search word).

Kind regards,

Ronald

Op 05-11-14 om 14:42 schreef Sandy:

> Top of this page: _Edit_ capture d ecran de 2014-11-05 08 41 54 
> https://cloud.githubusercontent.com/assets/1013356/4918476/9179fe00-64f1-11e4-83d8-7d5e8ae2222c.png
> 
>  — Reply to this email directly or view it on GitHub 
> https://github.com/OCA/banking/pull/55#issuecomment-61808136.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1

iQIcBAEBAgAGBQJUWkZUAAoJEKGB+BJNcQHTtaYP/RLSnlZVHYKfBrkxbZWAgh0J
bvQ93NN7nHblWwyyvfWxHxkDRh2r+D3pRwucNkRzOg6g4DlCrmBpZi9k5qojzulo
L6nAI3xQZAcdNZ6WPoaei+LHdrmJ4zAamHN28qOwwKNVl68azpcddm0Yq1BpqPwn
YR49K2YCLJnbJD/t33IX4GV1NHTUIzAWdTR0eLNhYQbE96Au5YtnUk7RLlXWLPf6
6D53eHMPDEnTcUAGY/uzeVz9ujzgzHDQVYIz0J/yzKpV+KqEm4wsucrW1Zvn/JnI
LsehkI4w+j10aRBomiv8CMMYhGC3B3yuasu4HbP8cqNw5KmoUtnjWumSbdZma6/o
vz5VAyUGAvWKF/AjvSFkEcfDWgArCM2dzrUZGxCzTG2Mzu2HETlDW1yi/c6lZPFn
AUDUFePWJxHISjuY4Kzm9I4IkKOakvY3AiAhyMC+ShxeDFTgK0wBeEYsRshMlgKb
44NZ75v25yhCz9q8N4svA4J2hb2QV1AFgEYb8+kZ32J++M13ERwfc7v30TQluQ0/
5DeJjO5BEns50WU9lImgm0PF78mIgiWtgZCUYkzYtbYMea9ZzYSjNMlMnXEhhUTv
dfIFhM35BL5pEBLrYsXznLm1jD8SzguzsxKcYfaXbS8K8VLsgRB/TdA+InIFki6g
/m++6UQR3faXUP4f+GMd
=JJ1j
-----END PGP SIGNATURE-----

**Comment by bwrsandman** [comment]
@NL66278 Sorry, I misunderstood the question. Labels can be set by reviewers. I have taken out the needs fixing label.

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Comment by sbidoul** [comment]
:+1: (code review)

**Pull request merged**
