### PR TITLE
[17.0][MIG] account_banking_sepa_credit_transfer: Migration to 17.0

### PR DESCRIPTION
**Pull request by trisdoan**
Depends on:

- [account_banking_pain_base] <https://github.com/OCA/bank-payment/pull/1231>

### CODE REVIEW

**Comment by pedrobaeza** [comment]
`account_banking_pain_base` should come first, isn't it?

**Comment by trisdoan** [comment]
Hi @pedrobaeza , indeed, a PR for `account_banking_pain_base` is coming

**Comment by HaraldPanten** [comment]
Hi @trisdoan could you make the migration in separate PR's?

If you put several modules in the same PR, it's harder to review.

Thanks!

**Comment by pedrobaeza** [comment]
And you can cross-reference several PRs to check if everything goes well with this:

https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by trisdoan** [comment]
Hi @pedrobaeza, the runboat check is failed because of account_payment_order. Any idea how to fix ?

ERROR: Could not build wheels for odoo-addon-account_payment_order, odoo-addon-account_payment_partner, odoo-addon-account_payment_mode, which is required to install pyproject.toml-based projects

**Comment by HaraldPanten** [comment]
But you still have lots of files here. Most are not needed, as they are from other modules.

Captura de Pantalla 2024-03-06 a las 18 15 37

**Pull request closed without merging**
