### PR TITLE
[MIG][14.0] account_banking_mandate_sale

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Travis is now green.

**Comment by patrickrwilson** [comment]
@alexis-via Thanks for your work, can you add test coverage please? Once green I will review it.

**Comment by Freni-OSI** [comment]
can you improve test coverage? @alexis-via

**Comment by Chanakya-OSI** [comment]
Can you rebase it with  OCA/bank-payment/14.0 @alexis-via

**Comment by alexis-via** [comment]
I rebased it. Now that v15 is out, maybe it's a good time to merge this "old" v14 PR :)

**Pull request merged**
