### PR TITLE
8.0 [Fix]Fix an error when no payment_order_ids

### PR DESCRIPTION
**Pull request by jlaloux**
[8.0][Fix] an error when no payment_order_ids

### CODE REVIEW

**Comment by pedrobaeza** [comment]
In v8, you don't need this artifacts anymore, because False values are propagated through null records. The only doubt I have is about the index getting an error, but if it's the case, you only need to put: `ref = self.payment_order_ids.reference` instead.

**Comment by jlaloux** [comment]
Yes you're right... old habits to forget ^^. And indeed, i encounter this problem because of the index

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
