### PR TITLE
[16.0][ADD] account_banking_mandate_sale_contact: new module

### PR DESCRIPTION
**Pull request by Tisho99**
Combination of account_banking_mandate_sale and account_banking_mandate_contact.

Depends of #1233

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten @jaimermaccione  Could u review??

**Review by Jaimermaccione — APPROVED** [review]
LGTM Functional review on local enviroment

**Review by HaraldPanten — APPROVED** [review]
Functional review. Tested in runboat

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
