### PR TITLE
[10.0][IMP] Add Italian SEPA SDD CBI Support

### PR DESCRIPTION
**Pull request by robyf70**
Hi,

with this PR I've added the Italian CBI SEPA SDD support. It's currently working since several months now without any issue on several Italian banks.

In particular there is one change which need to be discussed, the  because I haven't found a different way to address it. Actually I've added the scheme selection under account.payment.order because this is necessary as per payment order, so I would like to know if you have a different approach for that.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should go in OCA/l10n-italy

**Comment by robyf70** [comment]
I saw that this repo has German related SEPA things no?

**Comment by pedrobaeza** [comment]
Well, that's an historic error IMO, but it also needs less different things.

**Comment by robyf70** [comment]
the main problem is that it isn't easy to have it in OCA/l10n_italy, it's a bit "intrusive" patch because has to touch certain parts to work at best

**Comment by pedrobaeza** [comment]
Then propose here hooks for easing that task.

**Comment by robyf70** [comment]
Ok! The PR I've proposed aim that. I've divided it in 3 patches to monitor and rollback the changes and I did already all checks to verify that all previous things are still working as before.

**Comment by pedrobaeza** [comment]
I see a lot of specific Italian code here. Please open a new one only including hook methods for the things you need.

**Comment by robyf70** [comment]
The specific Italian code are surrounded by if to check if we are in the CBI specs, the else follow the standard code.

**Comment by robyf70** [comment]
>  Please open a new one only including hook methods for the things you need.

Let me check what is possible to do here

**Pull request closed without merging**
