### PR TITLE
[14.0][FW] [13.0] [account_payment_purchase][fix] Only issue a warning message if the PO had a non-blank payment mode or bank.

### PR DESCRIPTION
**Pull request by hailangvn**
Port of #809 from 13.0 to 14.0.

### CODE REVIEW

**Comment by TDu** [comment]
Looking at this comment https://github.com/OCA/bank-payment/pull/807#issuecomment-825761300 for the PR #807 It is not needed for v14.
It should probably be removed from this port.

**Comment by hailangvn** [comment]
Thanks @TDu for the comment. This PR has been updated.

**Review by TDu — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by hailangvn** [comment]
Thanks @pedrobaeza for triggered the merge. Somehow it stuck. Would you please trigger again or advise what should we do? Thanks in advance.

**Pull request merged**
