### PR TITLE
[9.0][FIX] account_payment_mode: ACL for portal group in account.payment.mode model

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to put groups=employee in the view that adds the payment mode?

Any way, change module version number

**Comment by sergio-teruel** [comment]
@pedrobaeza No, because a portl user wants view this information in his invoice

**Comment by pedrobaeza** [comment]
My comment is still valid with what I'm saying

**Comment by pedrobaeza** [comment]
But where is this seen? You don't add special QWeb fields for this, so it's a side effect more than the intended behavior.

**Comment by sergio-teruel** [comment]
Account_payyment_partner module adds info to report invoice, I could create this ACL in this module, but is in account_payment_mode where the model is created
https://github.com/OCA/bank-payment/blob/9.0/account_payment_partner/views/report_invoice.xml#L12

**Comment by pedrobaeza** [comment]
Ok, but as said in other place, this makes that any portal user sees all partner banks. Add record rule.

**Comment by rafaelbn** [comment]
So, what should we do here @sergio-teruel @pedrobaeza ? Close it?

**Comment by pedrobaeza** [comment]
Yes, closing it.

**Pull request closed without merging**
