### PR TITLE
[11.0] only generate FinInstId PstlAdr for some pain flavors

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
This is a forward port and fix of https://github.com/OCA/bank-payment/commit/7bf8d6aa8dfe7d738b55d6e77564d952afec2874 (10.0), which was erroneously reverted in #517 (sorry for the noise). 

Also providing a hook to fix issue https://github.com/OCA/bank-payment/issues/515 raised by l10n-switzerland.

**Review by pedrobaeza — APPROVED** [review]

**Review by j-zaballa — APPROVED** [review]

**Comment by ecino** [comment]
This is becoming an old issue and we are having troubles with pain files in Switzerland since end of last year. I propose that we merge this with high priority.

**Review by ecino — APPROVED** [review]

**Review by Byloth — APPROVED** [review]

**Comment by ecino** [comment]
Wait.. isn't it conflicting with what has been changed in v10 ? See 6bca6c3010d714573f67635d8a22dbd4fe94db77
In v10 a new field has been added to be able to manually activate or not the address, should we use the same mechanism in v11 instead of adding this method that must be then updated for each plain flavor?

**Pull request merged**
