### PR TITLE
Add the button to mark as done a payment order.

### PR DESCRIPTION
**Pull request by BT-cserra**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
Hi,

I'm not sure about this one. In v8 the transition to done was made automatically in upstream Odoo upon reconciliation (via transfer account).

In v9+ this feature is gone. But in practice it was not really useful and the only good way to track progress of a payment order is through reconciliation or bank statement matching (or unreconciliation through payment return).

So my question is: why/when would a user click on "done" on payment orders. In my mind, confirming the order has been correctly upload/sent to the bank marks the end of the process for the payment order itself, and the rest takes place through regular account reconciliation.

Actually I would rather remove the 'done' state.

**Comment by BT-fschubert** [comment]
Hi,
we added this button due to customers demand and the relation was lost to get this state automatically - from my point of view it is an intermediate step until a useful relation is either found on odoo core or added to a useful trigger in a bank-payment module. (We didn't had the time to search for a final approach).
I disagree to remove the "done" state due to usability reasons, cause related to our manual intermediate solution the user has no chance to see a difference between "Uploaded" and "Done" and he is conditioned to have an end of a process with state "Done".

**Review by tbaden — APPROVED** [review]
code review: lgtm

pro done state for a clean end in process

**Comment by pedrobaeza** [comment]
@sbidoul your final call

**Comment by KingLeo40** [comment]
Hello

**Comment by KingLeo40** [comment]
docs/content/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository.md

**Comment by KingLeo40** [comment]
I got the minner

**Comment by KingLeo40** [comment]
account_banking_mandate/__manifest__.py

**Pull request merged**
