### PR TITLE
[IMP] account_payment_order: add button to view business document

### PR DESCRIPTION
**Pull request by sbidoul**
Quick access to business document on payment lines.

### CODE REVIEW

**Comment by sbidoul** [comment]
I've been wanting to do this for a long time.

Very useful for people who need to validate payment orders that have been prepared by others.

image

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
@SAnnabelle what do you think of this one?

**Review by AnizR — APPROVED** [review]
Code LGTM, great new feature!

**Comment by SAnnabelle** [comment]
Functionally, I think it would be better to have a smart button to go to all the related business documents. 

Because if people want to check all the invoices, with the current development, they have to click on view and then go back to the payment order to see the next invoice. 

A smart button would make it possible to have all the invoices and simply navigate from one invoice to another using the arrows. The user could open this smart button on one screen and work on the payment order on another screen. This would make it easy to make any changes to the payment order.

**Comment by adrienpeiffer** [comment]
On the other hand, it's great to be able to open the document linked to a payment line directly without searching in many invoices. The best thing would be to combine the two solutions to answer different use cases. Add a smartbutton in addition to what's set up here. Let's merge this one as is for the moment.

**Review by adrienpeiffer — APPROVED** [review]

**Comment by alexis-via** [comment]
FYI, the smart button is implemented in OCA/bank-payment-alternative v18

**Pull request merged**
