### PR TITLE
8.0 FIX bug #111: crash when generating SEPA credit transfer file

### PR DESCRIPTION
**Pull request by alexis-via**
Please refer to the bug report #111 for the explainations. In fact, the commit just goes back to the code of v7.0, which worked well.

### CODE REVIEW

**Comment by alexis-via** [comment]
Note that, without this patch, we CANNOT EVEN GENERATE A SEPA CREDIT TRANSFER FILE on v8 !!! We shouldn't be proud of that, so let's patch this rapidly !

**Comment by guewen** [comment]
:+1:

**Comment by nbessi** [comment]
This is delicate the revert is not a full revert of 
Https://github.com/OCA/bank-payment/commit/791370ec7d34505c48c18f48702511cbed2d5bf9

This commit will allows the generate file but will also probably break branch code that depends on it like the 'ES' one. That probably means the fields is required by many module and should be declared else where. I did not find the bug related to the commit so I want to have @pedrobaesa advice on this one. 

An other point is that this modification greenify Travis. That odd and maybe means a test case is missing. 

I would be in favour of merging it. But I would like in parallel to have  a related bug report with corrective steps or a confirmation that code is fine as is.

**Comment by sbidoul** [comment]
As I read it, the version before 791370ec7d34505c4 was broken in the same way for ES but for ES only.

**Comment by pedrobaeza** [comment]
Yeah, that's correct. This is inherited code from 7.0 that I assume correct and make it general taking "partial information". I have to investigate if SEPA creditor identifier is also required for SEPA credit transfer. If so, solution is to move the field from _account_direct_debit_ to _account_banking_pain_base_.

I'll tell you ASAP.

**Comment by alexis-via** [comment]
@pedrobaeza Could we move forward on this ? This bug is really critical, because we can't generate a SEPA credit transfer on v8...

**Comment by sbidoul** [comment]
I agree with @alexis-via, we must merge this now, and provide a more complete in another PR if necessary. We can't leave SEPA credit transfer in a broken state in this repo.

If nobody objects, I'll merge tomorrow.

**Comment by pedrobaeza** [comment]
Sorry for the delay, but I query one expert, and I was waiting for the answer. Let me check tonight by myself, and I'll give a solution.

**Comment by sbidoul** [comment]
Thanks, Pedro!

**Comment by pedrobaeza** [comment]
As I can see in https://businessbanking.bankofireland.com/fs/doc/wysiwyg/sepa-credit-transfer-pain-001-001-03-xml-file-structure-july-2013.pdf (page 8), <InitgPty> section is also mandatory for credit transfer, so we have to make it another way. I'm going to prepare another PR with the following changes:
- Move field to account_banking_pain_base.
- Change export routine to raise an exception if this data is not filled.

I expect to have it tonight.

Stay tuned.

**Comment by pedrobaeza** [comment]
I have made #131 for solving properly this issue. Please check.

**Comment by dgouthiere** [comment]
Dear All, I am a new joiner, My name is David. Please correct me if this comment is not at the right place.
I arrive on this forum because impacted by non-working functionality when exporting SCT payment files.  I read your discussions and believe something is not 100% correct from the start point. 
My recommendation would be  to start from Febelfin pain standard.
InitiatingParty  exists for SCT and SDD.
InitiatingParty is only part of the groupheader and identify the payment initiator - will be a debtor in case  case of SCT and a creditor in case of SDD.  But no matter the role of the initiator because it does not affect the payment  infomation.  It is more an audit information for the receiving bank. But if not correct, the file is rejected by the bank.
The rules are clear in Febelfin  documentation (available on Febelfin website)
• InitiatingParty is mandatory  
• It can be a name (Max70text) AND / OR Identification     (yes, the remitter can mention both info)
• If identification is used, it must be :
o   BICorBEI   = BIC (if financial institution) 
OR
o   Other which consist of two mandatory informations
 Identification (a  Max35 text identification)   AND
 Issuer (a  Max35 text identification)
In Belgium, when the Initiator is a company, Febelfin request Identification to be the Enterprise nr (TVA nr in 10 digits) AND Issuer must be '"KBO-BCE"
I do not know special rules for other countries (ES, ...)
Febelfin is a standard based on ISO20022 - in fact a subset of ISO20022 and respect the same naming convention. My advice would be to keep the same naming in Odoo modules.
InitiatingParty exists for  SCT and SDD, with same layout but however small differences. (issuer is not mandatory for non BE company when Other is used).  
Managing SDD and SCT beeing two different businesses , my recommendation would be to manage the 2 applications separately.

https://www.febelfin.be/en/standards-distance-banking

Perhaps is my understanding not complete, then please let me know
Many thanks for your attention,
David

**Comment by yvaucher** [comment]
#131 was superseeded by #172 

@pedrobaeza Should we close this one?

@dgouthiere Thanks for your input, the code was patched have you tried with the last version? I don't know if your remark was taken into account though.

**Comment by pedrobaeza** [comment]
Yeah, I close it

**Pull request closed without merging**
