### PR TITLE
[FIX] Fixed Error when create new payment method

### PR DESCRIPTION
**Pull request by Nikul-OSI**
Fixed https://github.com/OCA/bank-payment/issues/896

**Steps to reproduce:**
1. Go to Accounting/Invoicing -> Configuration -> Payment Methods
2. Create new method

image

3. Save Record

ERROR:

image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The video in the issue is broken. Can you please add the steps to reproduce the problem by text? Also a regression test would be welcome.

**Comment by pedrobaeza** [comment]
And another, please follow the commit message guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by Nikul-OSI** [comment]
@pedrobaeza Already here https://github.com/OCA/bank-payment/issues/896, But different version.

When we try to create payment method that time got Error.

**Comment by pedrobaeza** [comment]
The video in such issue is broken, so I can't see the steps to reproduce the problem.

**Comment by Nikul-OSI** [comment]
Yes @pedrobaeza , In this video when create simple payment method that time broken. I added steps with error.

**Comment by pedrobaeza** [comment]
The problem is not in this module, but in Odoo code:

https://github.com/odoo/odoo/blob/a7be194f731370db0d8b0a2075e67676708fbd94/addons/account/models/account_payment_method.py#L28

The previous line should be:

```
information = methods_info.get(method.code, {})
```

instead of just

```
information = methods_info.get(method.code)
```

so don't put here code that is not related.

Closing this.

Please open instead a PR in Odoo solving the problem. It's also happening in 15.0.

**Comment by Nikul-OSI** [comment]
Yes, I knew, But in this code, I suggested to the user, they only set the **self._get_payment_method_information().keys()** code.

https://github.com/OCA/bank-payment/pull/1079/files#diff-1957a14450d19e93d0b1f1eb50d968293c0c998896604c36d5113a317028abc2R55

**Comment by pedrobaeza** [comment]
This is not the place to do that. Better fix the source problem in odoo/odoo.

**Comment by Nikul-OSI** [comment]
@pedrobaeza I created https://github.com/odoo/odoo/issues/121239

**Pull request closed without merging**
