### PR TITLE
[FIX] _check_payment_mode_company_constrains

### PR DESCRIPTION
**Pull request by mileo**
Can breaks multi company environments, for example: https://travis-ci.org/github/OCA/l10n-brazil/jobs/722154732#L2375

### CODE REVIEW

**Review by renatonlima — COMMENTED** [review]
@mileo This is not necessary because in module account_payment_mode has one ir.rule for multi-company https://github.com/OCA/bank-payment/blob/061e1dcddadf6cd2a48177bee4075212a4a38a00/account_payment_mode/security/account_payment_mode.xml#L4

**Comment by mileo** [comment]
Onchange of odoo/sale: https://github.com/odoo/odoo/blob/12.0/addons/sale/models/sale.py#L477-L490

Is called without company, than this can handle some unexpected behavior at multi company environment. 

When the company of the sales order is different from the user who confirms it.

**Review by marcelsavegnago — APPROVED** [review]

**Review by jpcarassato — APPROVED** [review]

**Review by luismalta — APPROVED** [review]

**Pull request merged**
