### PR TITLE
[FIX] Module base_iban_not_required:

### PR DESCRIPTION
**Pull request by NL66278**
```
- Removed module from the __unported__ directory, because
  module is no longer needed on odoo 8.0, therefore does not need
  porting.
```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is not needed?

**Comment by NL66278** [comment]
The module removes a constraint that in odoo 8.0 is already non existent.

**Comment by pedrobaeza** [comment]
OK, thanks for the explanation :+1:

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
