### PR TITLE
[16.0][MIG] account_payment_purchase_stock

### PR DESCRIPTION
**Pull request by SodexisTeam**
This module depends on account_payment_purchase.
There is an existing PR for the migration of account_payment_purchase in the repository.
https://github.com/OCA/bank-payment/pull/1004

### CODE REVIEW

**Comment by stefan-tecnativa** [comment]
The `account_payment_purchase` module has already been merged, so you can remove your requirements commit. But check why tests are failling

**Comment by amkarthik** [comment]
@stefan-tecnativa 
Removed the dependency. All tests succeeded now.

**Review by stefan-tecnativa — APPROVED** [review]
LGTM

**Review by atchuthan — APPROVED** [review]
:+1:

**Pull request merged**
