### PR TITLE
[15.0][MIG]account_banking_pain_base

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/bank-payment/pull/885

### CODE REVIEW

**Comment by manuelregidor** [comment]
@sbidoul @pedrobaeza 

Pre-commit is showing this error: ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repobwmo42hu/py_env-python3/lib/python3.10/site-packages/click/__init__.py)

Any idea? Thank you.

**Comment by pedrobaeza** [comment]
Please investigate a bit more before pinging:

https://github.com/OCA/oca-addons-repo-template/issues/133

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza Do you want us to make a PR for this repository in order to FIX black/click? Or do you prefer to do it manually? Not sure about how do you use to organize for solving these kind of issues.

THX.

**Comment by pedrobaeza** [comment]
I can do it, but not now, so if you want to make the PR applying the new copier template, go ahead, and I'll merge it.

**Comment by HaraldPanten** [comment]
Sorry Pedro,

We've been having a look but we couldn't really understand all the changes we need to do. I prefer to make sure before making others wasting their time.

We will take some notes once you solve this in order to be able to carry out the next fixes. THX

**Comment by pedrobaeza** [comment]
Please rebase. It should be OK now.

**Comment by HaraldPanten** [comment]
@misern2 @ValentinVinagre @rafaelbn Could you review, please?

**Review by HaraldPanten — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by rafaelbn — APPROVED** [review]
👍 Thanks!

**Pull request merged**
