### PR TITLE
[9.0][IMP] account_banking_mandate: Put binary field as attachment

### PR DESCRIPTION
**Pull request by pedrobaeza**
For not wasting space in DB. Migration scripts included (requires openupgradelib).

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@alexis-via @sbidoul please check this annoying "oldy" that I have found. I have made this for the lower supported version, but I'll forward port to rest of the versions as soon as this is approved.

**Review by alexis-via — APPROVED** [review]
code review, no tests

**Review by sbidoul — APPROVED** [review]
Good idea! 

Code review only.

**Review by etobella — APPROVED** [review]
LGTM :+1: 
It is easier to unterstand

**Comment by pedrobaeza** [comment]
Cherry picked in:

* v10: 490d7878a01e16ddd8182f905e9710b8719f4668
* v11: 6f8af30a551e67f912e81ec1e141445ad8832f39
* v12: b1ab887595fa2406fbac85e876b88a1a71040502

**Pull request merged**
