### PR TITLE
[12.0][REF] account_payment_purchase: make independent from stock

### PR DESCRIPTION
**Pull request by astirpe**
In Odoo V12 the module `purchase` does not depend from module `stock` anymore.

This PR is a proposal to split module `account_payment_purchase` in order to make it not dependent from `stock` as well. This will avoid to  force the installation of `stock` if not needed, saving extra costs of purchasing an unused Odoo app.

For this purpose, a new auto-installable module is added: `account_payment_purchase_stock`.

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't agree with this. This change can't be done in a stable version. Do it for 13, but not here. It will break installations.

**Comment by astirpe** [comment]
Thanks!

**Comment by MiquelRForgeFlow** [comment]
Included in v13 migration https://github.com/OCA/bank-payment/pull/674 😉

**Comment by astirpe** [comment]
Shall I close this PR?

**Pull request closed without merging**
