### PR TITLE
[16.0][MIG] account_payment_order_transfer_journal

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
superceeds https://github.com/OCA/bank-payment/pull/1243 and https://github.com/OCA/bank-payment/pull/1108

**Comment by dreispt** [comment]
Supersedes already reviewed https://github.com/OCA/bank-payment/pull/1108

**Review by dreispt — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@dreispt 
Daniel,

You tried an /ocabot merge nobump (which failed because of a typo).
But this should be /ocabot merge minor (new small feature which requires module upgrade to activate it).
Can you do so ?

Tx,
Luc

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
