### PR TITLE
[16.0][MIG] account_payment_order_grouped_output: 16.0

### PR DESCRIPTION
**Pull request by ferran-S73**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together first 4 commits, and check how I modified the main comment to see the status of the depending PR.

**Comment by pedrobaeza** [comment]
It's better that you start from the migration to 15.0 on #1055, because the code you have changed for getting the grouped output liquidity account is not totally correct.

**Comment by ferran-S73** [comment]
Hey @pedrobaeza migration done form 15.0

**Comment by pedrobaeza** [comment]
Please squash together these commits and it's good to go:

Selección_065

**Comment by ferran-S73** [comment]
> Please squash together these commits and it's good to go:
> 
> Selección_065

@pedrobaeza done!

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_payment_order_grouped_output
/ocabot merge nobump

**Pull request merged**
