### PR TITLE
[16.0][IMP] account_payment_order: update payment reference on open payment order

### PR DESCRIPTION
**Pull request by luc-demeyer**
This commits adds the possibility to update the payment reference on a payment transaction before generating XML file.

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why doing this through a wizard? Isn't better to put the payment tree editable inside the payment order, and allow to change the reference on the corresponding payment order state?

**Comment by luc-demeyer** [comment]
payment order is confirmed hence imho button gives a better signal to the end user that he is changing the payment reference on a confirmed object.
@alexis-via what do you think ?

**Comment by pedrobaeza** [comment]
OK conceptually. Please rebase and fix conflicts for merging this.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
rebase done hence imho this one is ready for merge.

**Comment by pedrobaeza** [comment]
Please fw-port it to v17:

/ocabot merge minor

**Pull request merged**
