### PR TITLE
[15.0][MIG] account_banking_mandate

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
I remove the code of https://github.com/OCA/bank-payment/pull/243 because it is not needed any more (the problem was specific to older versions of Odoo).

**Comment by MiquelRForgeFlow** [comment]
please cherry-pick https://github.com/OCA/bank-payment/commit/f4bac2f5620316c2b0008e8517b222b9c402c5ac

**Comment by HaraldPanten** [comment]
@alexis-via account_payment_order has been merged. You can continue with this one 👍

**Comment by HaraldPanten** [comment]
Hi @alexis-via  Will you continue this PR, or do you prefer us to supersede this one by another one?

THX!

**Review by rafaelbn — APPROVED** [review]
Great! 👍 Please @alexis-via review comments like https://github.com/OCA/bank-payment/pull/883#issuecomment-1062041099

Could you please rebase? Let go with this one 😄

**Comment by HaraldPanten** [comment]
Closed as it has been superseded by another one

**Pull request closed without merging**
