### PR TITLE
[14.0] account_payment_sale: add payment_mode_id in sale.report

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Tests are green at last!

**Comment by matteoopenf** [comment]
I open this issue https://github.com/OCA/bank-payment/issues/1059

**Comment by matteoopenf** [comment]
is it possibile fix the pre-commit?

**Comment by matteoopenf** [comment]
thank you @alexis-via

**Review by matteoopenf — APPROVED** [review]
LGTM

**Review by patrickt-oforce — APPROVED** [review]
LGTM

**Comment by lorenzoallegrucci** [comment]
LGTM

**Review by lorenzoallegrucci — APPROVED** [review]

**Comment by matteoopenf** [comment]
@OCA/banking-maintainers  is it possibile  merge?

**Comment by matteoopenf** [comment]
> /ocabot merge minor

thank you

**Pull request merged**
