### PR TITLE
[9.0][FIX] account_payment_partner: ACL for portal group for res.partner.bank model

### PR DESCRIPTION
**Pull request by sergio-teruel**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sergio-teruel please check the Travis status on this.

**Comment by sergio-teruel** [comment]
@pedrobaeza Ready for merge

**Comment by pedrobaeza** [comment]
But with this, you are giving access to any portal user to all your partners' bank accounts. You should restrict it by a record rule, which is not good for other that needs full access, or change it in the place where it fails (like the sudo in invoices).

**Comment by sergio-teruel** [comment]
Ok, security read rule added

**Review by chienandalu — CHANGES_REQUESTED** [review]
Failing on:

```
ParseError: "External ID not found in the system: account_payment_partner.model_account_banking_mandate" while parsing /home/travis/build/OCA/bank-payment/account_payment_partner/security/account_payment_partner_security.xml:5, near
```

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This PR has several problems:

* Banking mandate model is not in this module, but on account_banking_mandate module.
* You are giving access to portal users to all partner banks.

**Pull request closed without merging**
