### PR TITLE
[IMP] review sql request for migration fast treatment

### PR DESCRIPTION
**Pull request by jco-subteno-it**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think the change is faster. Subqueries are always slower.

**Comment by jco-subteno-it** [comment]
@pedrobaeza I go from one hour of treatment to 5 minutes on my client migration

**Comment by pedrobaeza** [comment]
The problem then should be a missing index in the involved fields, but subquey shouldn't be the solution.

**Comment by jco-subteno-it** [comment]
i agree

**Comment by pedrobaeza** [comment]
Then better to add the index where proceeding, or in the normal use of the module, the problem will appear when unlinking cascade or similar.

**Comment by dreispt** [comment]
@jco-subteno-it can we close?

**Comment by jco-subteno-it** [comment]
Yes sorry

**Comment by pedrobaeza** [comment]
If the index is something that can be incorporated to the module, just tell it or do a PR adding such thing.

**Pull request closed without merging**
