### PR TITLE
Expand PAIN support

### PR DESCRIPTION
**Pull request by sbidoul**
This is a partial rewrite of #490 / #491 

Each commit should be self explanatory.

### CODE REVIEW

**Comment by sbidoul** [comment]
@pedrobaeza @alexis-via would you like to review this?

**Comment by sbidoul** [comment]
@alexis-via I fixed `InstrId` for direct debit in b58d8bbdb3ce1f064b6b3c85ba8298ebf46f3f5d.

**Review by alexis-via — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul can you please forward-port it to v11?

**Comment by pedrobaeza** [comment]
@sbidoul any news?

**Comment by sbidoul** [comment]
Not had time yet.

**Comment by pedrobaeza** [comment]
OK, thanks for the followup.

**Comment by sbidoul** [comment]
@pedrobaeza cherry-pick to 11.0 done

**Pull request merged**
