### PR TITLE
[15.0][IMP]account_payment_order: Add activities to account.payment.order model

### PR DESCRIPTION
**Pull request by manuelregidor**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
I relaunched the pre-commit, to see if it fails again in this branch

**Comment by HaraldPanten** [comment]
Any changes in Flake 8?

--> [INFO] Initializing environment for https://gitlab.com/PyCQA/flake8.   is the one that fails.

Maybe you could give us any clue, @pedrobaeza

**Comment by pedrobaeza** [comment]
I'm on it: https://github.com/OCA/bank-payment/pull/986

**Comment by ValentinVinagre** [comment]
thanks @pedrobaeza

**Pull request merged**
