### PR TITLE
[12.0][FIX] account_payment_sale: Compatibility with modules as account_banking_sepa_direct_debit

### PR DESCRIPTION
**Pull request by chienandalu**
Forward port of https://github.com/OCA/bank-payment/pull/667

cc @Tecnativa TT26142

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@carlosdauden can you please explain the motivations for this change in 11.0?

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@carlosdauden we are waiting for your explanation for merging this.

**Review by HaraldPanten — APPROVED** [review]

**Comment by carlosdauden** [comment]
Without this change if you have a direct debit payment mode with bank_account_link == 'fixed' the field fixed_journal_id.bank_account_id is setted in partner_bank_id field.

Payment mode: Santander Direct Debit with Fixed Journal: Santander ES11 1111 1111 1111 1111
Sale Partner bank account: ES22 2222 2222 2222 2222

Without this change invoice is created with partner bank = Santander ES11 1111 1111 1111 1111

**Comment by pedrobaeza** [comment]
OK, thanks for the extra explanation, @carlosdauden. Check the commit message I have put according to this explanation:
```
 [FIX] account_payment_sale: Compatibility with account_banking_sepa_direct_debit

Steps to reproduce the problem:

- Set a payment mode with fixed journal and set the journal with bank account A.
- Create a sales order and put bank account B.
- Create invoice.
- Bank account in invoice is A instead of B.
```
Please take into account next time you do these changes for avoiding further questions. It's also advisable to focus the text on generic compact data for being clearer.

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Cherry-pick for v13 in 5b7e05cb5777b2e524013e6de57200e4e8725410

**Pull request merged**
