### PR TITLE
[IMP][account_banking_payment_transfer] Consider invoice reference on move line

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Consider invoice reference for the move line on transfer account if there is only one payment line

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I would prefer to have both references in the move name. For example: `payment_line_name (Invoice ref)`

**Comment by adrienpeiffer** [comment]
@pedrobaeza Thanks ! It's done

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
