### PR TITLE
[10.0][MIG] account_payment_purchase

### PR DESCRIPTION
**Pull request by Abranes**
Standard migration from v9.0 as talk in #352.

@hbrunn @pedrobaeza @Jortolsa

### CODE REVIEW

**Review by Jortolsa-S73 — APPROVED** [review]

**Comment by Jortolsa-S73** [comment]
Tested and working

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Review by hbrunn — APPROVED** [review]
thanks

**Comment by Abranes** [comment]
@pedrobaeza Done!

**Comment by Abranes** [comment]
@pedrobaeza any news about this? It's ready to merge?

**Comment by Abranes** [comment]
@pedrobaeza @hbrunn any other suggestions for change or is ready to merge?

**Pull request merged**
