### PR TITLE
[FIX][13.0] account_payment_order_return frezze time to run properly …

### PR DESCRIPTION
**Pull request by i-vyshnevska**
…date depandant test

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As I have commented other times, I prefer to not introduce new requirements (even in tests) for a module already in the repo. This will break CIs that don't have this requirement set. Please set instead the value in the corresponding field to a fixed value for avoiding the problem, that I suppose comes from the combination of timezones + test running around midnight.

**Comment by i-vyshnevska** [comment]
> As I have commented other times, I prefer to not introduce new requirements (even in tests) for a module already in the repo. This will break CIs that don't have this requirement set. Please set instead the value in the corresponding field to a fixed value for avoiding the problem, that I suppose comes from the combination of timezones + test running around midnight.

freezegun was introduced in odoo14 as a magor way to handle dates in tests

**Comment by pedrobaeza** [comment]
But this is 13.0

**Comment by i-vyshnevska** [comment]
@pedrobaeza sorry but IMO it doesn't worth fixing tests through haking the timezone when you have a ready tool that is standard even for the newest version, that is not considered with our time budget

**Comment by pedrobaeza** [comment]
I'm not saying to hack timezone, but to fix the needed field. Anyway, this is not failing unless being around midnight, so you can let it as is if not committing at that hours.

**Comment by pedrobaeza** [comment]
It may be enough to use `fields.Date.context_today(self.env.user)` in the affected field.

**Comment by pedrobaeza** [comment]
I did the needed fix in #925, so closing.

**Comment by Razz-786** [comment]
How can i hack imo

**Pull request closed without merging**
