### PR TITLE
[16.0][MIG] account_payment_order: Migration to 16.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
Commit history redone from scratch + squash administrative commits + bring and squash changes for 16.0 from #972 for finishing the migration.

@Tecnativa

### CODE REVIEW

**Comment by acsonefho** [comment]
@pedrobaeza Did you miss the migration folder? Or did you remove it yourself? Any particular reason?

**Comment by pedrobaeza** [comment]
There are no migration scripts. They all happened in previous versions, not for this one.

**Comment by acsonefho** [comment]
@pedrobaeza Into the original PR, they are 2 files:
https://github.com/OCA/bank-payment/pull/972/files#diff-560ceefd18093597e6b6be6dd7e0bc536489a528287758ab35dfa15e35511bde

**Comment by pedrobaeza** [comment]
And they are incorrect. As said, they belong to older versions, where the refactoring to native payment happened. You reach this version with that refactoring done.

**Pull request merged**
