### PR TITLE
[IMP] set complete domain before calling extend_payment_order_domain met...

### PR DESCRIPTION
**Pull request by adrienpeiffer**
...hod on account_banking_payment_export addons

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think there was a reason for adding that domain afterwards, but I can't find it now, so :+1:

**Comment by sbidoul** [comment]
This is useful to give extensions full control on the domain.

:+1:

**Comment by adrienpeiffer** [comment]
Anyone willing to review this one?

**Comment by pedrobaeza** [comment]
2 approvals is enough now.

I merge.

**Comment by adrienpeiffer** [comment]
Thanks @pedrobaeza !

**Pull request merged**
