### PR TITLE
[8.0] npg modules - account_banking_make_deposit, account_banking_reconciliation

### PR DESCRIPTION
**Pull request by bwrsandman**
Porting NPG modules from https://code.launchpad.net/openerp-usa

Many improvements and fixes have been added including multi-company support.

8.0 version of #144

### CODE REVIEW

**Comment by bwrsandman** [comment]
@pedrobaeza @dreispt @veloutin @joaoalf @gurneyalex could we get a review please?

**Comment by max3903** [comment]
Access rights are missing. Admin is not in any of the 4 created groups.
This was fixed in version 7.0.

**Comment by bwrsandman** [comment]
@max3903 cherrypicked missing commits from 7.0, there should be the groups now

**Comment by max3903** [comment]
Unable to login on database 3111910-191-e60091-all

**Comment by bwrsandman** [comment]
except_orm: ('Error', u"You try to install module 'account_banking_reconciliation' that depends on module 'account_cutoff_base'.\nBut the latter module is not available in your system.")

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Do these modules still apply to current bank-payment suite?

**Comment by max3903** [comment]
@pedrobaeza Unless you have a solution to manage deposit ticket (list of checks to deposit at the bank counter) and bank statement reconciliation (check and clear transactions appearing on the monthly bank statement), I think they do.

**Comment by pedrobaeza** [comment]
I'm doing that with account_banking_payment_transfer + account_banking_payment_export. I define a payment mode called "Deposit ticket" (or similar), with a transfer account. I make a direct debit order, collecting all the invoices that form the deposit, and move the balance automatically at order validation.

Then, the new balance can be automatically reconciled with the bank statement directly (if your transfer account allows to reconcile), or through this module: https://github.com/OCA/bank-statement-reconcile/tree/8.0/account_reconcile_payment_order.

So for me, there's no need of another module for the same purpose. Maybe we can add a special menu entry + some facilities (preconfigure payment mode for example) for the check deposit to make it easy to understand, but the tools are already there.

**Comment by pedrobaeza** [comment]
cc @jbeficent, maybe you're interested in this topic

**Comment by max3903** [comment]
@pedrobaeza Does your module provide a report with the list of checks included in the deposit and the total? Does it provide 2 groups to separate the preparation from the verification?

Regarding the bank statement reconciliation (which should be called clearing), how do you do that?

**Comment by pedrobaeza** [comment]
Payment order has already a report that can serve as the list of checks. As said, we can improve this thing through specific report if needed.

About preparation + verification, you can use several techniques:
- The verification can be done at posting state. AFAIK, ACSONE is doing something like that, using modules like https://github.com/OCA/bank-payment/tree/8.0/account_payment_include_draft_move
- Have 2 different journals for each step, and adding AR/AP from that journals (it can be done thanks to the provided import filters).
- Even developping a checkbox or state for easing things if you think so.

**Comment by pedrobaeza** [comment]
About the clearing, if you mean an automatic reconciliation when the date is due, that's something not develop by now, but can be also added to this suite easily.

**Comment by JordiBForgeFlow** [comment]
@max3903 Regarding account_banking_reconciliation, we've been using it in v7. But in v8, since the banking reconciliation has been improved, doesn't it make more sense to just use the standard reconciliation? 

The npg module had a feature by which the bank move lines would be imported to the bank statement, and the user would just 'flag' the entries that have cleared the bank. That would, in a practical sense, make it unnecessary to import the statement from the bank, but would work on the basis of visually comparing the move lines reported into the bank account in Odoo with those in the bank statement. 

In Odoo 8 you could do a similar thing by importing into the bank statement the unreconciled move lines from the checks/deposits transitory account that you used to pay invoices in the first place, so that you are 'pre-filling' the bank statement with the entries that are supposed to have cleared the bank. Then you just run the reconciliation wizard, which is the mechanism to confirm if the lines have truly cleared the bank. Once you're finished with the reconciliation wizard, you can remove any checks/deposits that were issued, but did not finally reach the bank.

**Comment by max3903** [comment]
@jbeficent, @pedrobaeza so if I read you well, we should close this pull request and abandon those 2 modules. Right?

**Comment by stephankeller** [comment]
Note: we have been using the two modules with some changes for all our customers in the US in V7 and V8.  I have been looking at what to do for V9.  Not only for new customers but also existing one that want to migrate.

@pedrobaeza I looked at account_banking_payment_transfer + account_banking_payment_export.  It looks great, but I don't think this will work for customers in the US.  They need to be able to enter the payment when they receive the check, then they accumulate the checks and at the time they go to the bank then need to enter the deposit (with the transfer from "in-transit account" to the final bank account).  It will not work for them to wait to have all the checks and then enter the payment order.  Also I think that it will be hard to convince them to enter one payment record for multiple partners, they are used to one invoice - one payment per partner (and as we discussed in another issue, they need to be able to register payment from the invoice).

@jbeficent For V8, I agree with you that it could have been done the way you describe but basically one would need to duplicate all the functionalities of account_banking_reconciliation:  import all the possible statement lines up to a date, make sure that the lines have not been imported in another statement yet, being able to refresh it in case a new payment need to be entered and/or to add bank fees, display total for deposits, total for checks, cleanup the line that are not needed at the end, add the 2 groups, etc….   At least for us, given that it is already done in account_banking_reconciliation, I don’t see the point of redoing it for V8.

For V9, I think we might be able to use the bank statement from Odoo for bank accounts that can be synchronized online.  In that case we have the exact bank statement lines that need to be reconciled/cleared, so we don’t have to simulate that part.   Also this way we can keep the accounting dashboard.  One thing we need to change is to not display the entries from account payable and account receivable, as in our case I believe it will confuse the user (we are working on that).   But for any bank account that can not be synchronized online or for which we can not import the lines, we have the same issue as for V8. Not 100% sure what we will do for that case.

I looked at using the Odoo batch deposit in V9, as far as I can tell it is not working well enough as it is, we would have to modify it to reproduce what  account_banking_make_deposit does, so we may as well just port that module to V9.

Pedro, I understand you don’t want those two module in bank-payment, so how about we move them to the US localization?  Maxime and I are part of the PSC,.  What do you think Maxime? @max3903

Thanks for taking the time to read.

**Comment by JordiBForgeFlow** [comment]
On Wed, Jun 8, 2016 at 12:43 AM, Stephan Keller notifications@github.com
wrote:

> Note: we have been using the two modules with some changes for all our
> customers in the US in V7 and V8. I have been looking at what to do for V9.
> Not only for new customers but also existing one that want to migrate.
> 
> @pedrobaeza https://github.com/pedrobaeza I looked at
> account_banking_payment_transfer + account_banking_payment_export. It looks
> great, but I don't think this will work for customers in the US. They need
> to be able to enter the payment when they receive the check, then they
> accumulate the checks and at the time they go to the bank then need to
> enter the deposit (with the transfer from "in-transit account" to the final
> bank account). It will not work for them to wait to have all the checks and
> then enter the payment order. Also I think that it will be hard to convince
> them to enter one payment record for multiple partners, they are used to
> one invoice - one payment per partner (and as we discussed in another
> issue, they need to be able to register payment from the invoice).
> 
> I agree. The electronic banking is slowly being adopted in the US, and most
> people continue to work the 'old way'.
> 
> @jbeficent https://github.com/jbeficent For V8, I agree with you that
> it could have been done the way you describe but basically one would need
> to duplicate all the functionalities of account_banking_reconciliation:
> import all the possible statement lines up to a date, make sure that the
> lines have not been imported in another statement yet, being able to
> refresh it in case a new payment need to be entered and/or to add bank
> fees, display total for deposits, total for checks, cleanup the line that
> are not needed at the end, add the 2 groups, etc…. At least for us, given
> that it is already done in account_banking_reconciliation, I don’t see the
> point of redoing it for V8.
> 
> @stephankeller, see our Bank Statement Reconciliation Summary module here:
> https://github.com/OCA/account-financial-reporting/pull/202. Documentation
> here:
> https://docs.google.com/document/d/1rzJX09nD6VlG_PbEtvBJqNXajXi7Th1H3ayWJNmgPdI/edit

It currently targets v8 but can be easily adjusted to v9.

I don't see any of the features of total for deposits, total for checks,
etc.. in Odoo 9 CE or EP. Would that be really needed? The reconciliation
summary report would provide these totals.

For V9, I think we might be able to use the bank statement from Odoo for

> bank accounts that can be synchronized online. In that case we have the
> exact bank statement lines that need to be reconciled/cleared, so we don’t
> have to simulate that part.
> 
> @stephankeller, but still you'd need the reconciliation summary report,
> which exists in EP but not in CE.

Also this way we can keep the accounting dashboard. One thing we need to

> change is to not display the entries from account payable and account
> receivable, as in our case I believe it will confuse the user (we are
> working on that).
> 
> @stephankeller, I have not seen this happening. Can you explain better
> what's happening?
> 
> But for any bank account that can not be synchronized online or for which
> we can not import the lines, we have the same issue as for V8. Not 100%
> sure what we will do for that case.
> 
> @stephankeller, I'd suggest adding a button 'Import payments and deposits',
> that would just enter the accounting entries that have not yet been
> reconciled. And again, if they did not clear the bank, should be removed
> once the reonciliation has finished, so that they can be used at a later
> stage (or you can keep them for the next reconcilation attempt).
> 
> I looked at using the Odoo batch deposit in V9, as far as I can tell it is
> not working well enough as it is, we would have to modify it to reproduce
> what account_banking_make_deposit does, so we may as well just port that
> module to V9.
> 
> @stephankeller. Agreed... we already discussed about this.
> 
> Pedro, I understand you don’t want those two module in bank-payment, so
> how about we move them to the US localization? Maxime and I are part of the
> PSC,. What do you think Maxime? @max3903 https://github.com/max3903
> 
> @stephankeller. These features are not specific to the US. I have seen them
> also needed in Singapore.
> 
> Thanks for taking the time to read.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/OCA/bank-payment/pull/191#issuecomment-224436899, or mute
> the thread
> https://github.com/notifications/unsubscribe/AHU_Vpc9vhVXrw3nQdMl8MecGf5_MJokks5qJfQugaJpZM4FPNUj
> .

## 

Jordi Ballester Alomar
CEO & Founder | Eficent
(+34) 629530707 | jordi.ballester@eficent.com | http://www.eficent.com
Twitter: https://twitter.com/jbeficent_erp | Linkedin:
https://www.linkedin.com/in/jordiballesteralomar

**Comment by max3903** [comment]
@stephankeller The features should be in bank-payment. @pedrobaeza and @jbeficent are suggesting to use existing modules and to improve them if you think a feature is missing.

**Comment by stephankeller** [comment]
@jbeficent https://github.com/jbeficent sorry for the delay answering.

> I agree. The electronic banking is slowly being adopted in the US, and most
> people continue to work the 'old way'.
> 
> Yes, it is necessary to keep both options.
> 
> @stephankeller, see our Bank Statement Reconciliation Summary module here:
> https://github.com/OCA/account-financial-reporting/pull/202. Documentation
> here:
> 
> https://docs.google.com/document/d/1rzJX09nD6VlG_PbEtvBJqNXajXi7Th1H3ayWJNmgPdI/edit
> 
> It currently targets v8 but can be easily adjusted to v9.

That looks good.

> I don't see any of the features of total for deposits, total for checks,
> etc.. in Odoo 9 CE or EP. Would that be really needed? The reconciliation
> summary report would provide these totals.

I was talking about account_banking_reconciliation, those fields appear
directly on the page while doing the reconciliation.  That helps to figure
out what is missing in the bank statement and you don't need to open
anything else, the equivalent here would be to have that on the
reconciliation window.

> For V9, I think we might be able to use the bank statement from Odoo for
> 
> > bank accounts that can be synchronized online. In that case we have the
> > exact bank statement lines that need to be reconciled/cleared, so we
> > don’t
> > have to simulate that part.
> > 
> > @stephankeller, but still you'd need the reconciliation summary report,
> > which exists in EP but not in CE.

Yes, it would be good to have it for CE as well.

> Also this way we can keep the accounting dashboard. One thing we need to
> 
> > change is to not display the entries from account payable and account
> > receivable, as in our case I believe it will confuse the user (we are
> > working on that).
> > 
> > @stephankeller, I have not seen this happening. Can you explain better
> > what's happening?

I am talking about the fact that account payable and account receivable
appears when you do a bank statement reconciliation, they appear in black
instead of blue.  For the customer we have, I don't think they want to see
the unpaid invoices in the reconciliation window.  Also, for them it is
somewhat confusing to see an invoice that is paid, but with not payment in
the "payment" window, so they want to enter a payment record for each
invoice.

> > But for any bank account that can not be synchronized online or for which
> > we can not import the lines, we have the same issue as for V8. Not 100%
> > sure what we will do for that case.
> > 
> > @stephankeller, I'd suggest adding a button 'Import payments and deposits',
> > that would just enter the accounting entries that have not yet been
> > reconciled. And again, if they did not clear the bank, should be removed
> > once the reonciliation has finished, so that they can be used at a later
> > stage (or you can keep them for the next reconcilation attempt).

I agree that the technique to pull the record in the statement line is
interesting and I will think about using it for V9.  I have some
reservation for environment where there are a lot of lines and one need to
figure out what are the line missing or not belonging to that statement.
Also some of the lines that are not part of the current statement will
probably be reconciled automatically when you click on the "reconcile"
button, so now the user as to unreconcile them.

> > I looked at using the Odoo batch deposit in V9, as far as I can tell it
> > is
> > not working well enough as it is, we would have to modify it to reproduce
> > what account_banking_make_deposit does, so we may as well just port that
> > module to V9.
> > 
> > @stephankeller. Agreed... we already discussed about this.

yes, so we are going to port the bank deposit module to V9.

> > Pedro, I understand you don’t want those two module in bank-payment, so
> > how about we move them to the US localization? Maxime and I are part of
> > the
> > PSC,. What do you think Maxime? @max3903 https://github.com/max3903
> > 
> > @stephankeller. These features are not specific to the US. I have seen them
> > also needed in Singapore.
> 
> ok, then they should be in Bank payment.  Specially the bank deposit I
> think.

Thanks,
Stephan.

## 

Stephan Keller, Ph. D.
CEO Sodexis, Inc.
Orlando/Longwood, FL
www.sodexis.com
Odoo Certified Expert
http://www.linkedin.com/in/stephankellersodexis
Phone: (407) 278-4917
Cell: (407) 202-8998

**Pull request closed without merging**
