### PR TITLE
[10.0][IMP] account_payment_order: select partner bank account automatically.

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by sbidoul** [comment]
Sounds good to me, but we need @alexis-via 's opinion.

**Comment by sbidoul** [comment]
This is useful when user populate the partner bank account after having validated the invoice.

**Review by sbidoul — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I have another complementary patch about auto-selecting bank accounts on invoices in progress. Meanwhile, this one is useful.

Please change module version number before I merge this.

**Comment by adrienpeiffer** [comment]
@pedrobaeza Thanks ! it's done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
