### PR TITLE
move BeautifulSoup import inside the methods

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by lmignon** [comment]
:-1: a double 'import' sounds as a terrible hack!  And the next time we need it in an other method we'll add a new import.. plz prefer a try catch on top of the file...

**Comment by gurneyalex** [comment]
@lmignon updated

**Comment by lmignon** [comment]
@gurneyalex :+1:  Thank you!

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1:

**Pull request merged**
