### PR TITLE
[16.0][IMP] account_banking_sepa_direct_debit: increase report signature space

### PR DESCRIPTION
**Pull request by Tisho99**
FW PORT OF https://github.com/OCA/bank-payment/pull/1258

T-6009

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
