### PR TITLE
[11.0][MIG] account_banking_mandate_sale

### PR DESCRIPTION
**Pull request by thinkwelltwd**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by thinkwelltwd** [comment]
> Please squash together adjacent "OCA Transbot.." commits 

Ok, that's now done.

**Comment by thinkwelltwd** [comment]
It would be nice to get this merged...

**Comment by pedrobaeza** [comment]
Please fix the migration commit name and I'll merge it, as it's basically the same as 10.0.

**Comment by thinkwelltwd** [comment]
> Please fix the migration commit name and I'll merge it, as it's basically the same as 10.0.

Ok, changed the name.

**Pull request closed without merging**
