### PR TITLE
[MIG] account_banking_mandate_sale: migration to 17.0

### PR DESCRIPTION
**Pull request by MarwanBHL**
Basic Migration to 17.0

### CODE REVIEW

**Review by luisDIXMIT — APPROVED** [review]
Tested on runboat. LGTM!

**Review by angelmoya — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
Please rebase and check the problem.

**Comment by MarwanBHL** [comment]
@pedrobaeza the problem seem to be the one mentioned in #1266

**Pull request merged**
