### PR TITLE
[FIX] account_banking_sepa_direct_debit: Fix report mandate. Adapt to bootstrap 4

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT19604

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please check the differences between v11:
Selección_007
and v12:
Selección_008

**Comment by sergio-teruel** [comment]
Ok!! I forgot offset column conversion.
Changes done!!

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Now it's correct, so merging for fixing the problem

/ocabot merge minor

**Comment by joramowuor** [comment]
merge pullrequest #638 file 201855085895400

**Pull request merged**
