### PR TITLE
[14.0][MIG] account_banking_pain_base

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We already did the port in #761, but both are still with Travis red.

**Comment by alexis-via** [comment]
Sorry for the double migration. I started a few days ago, but I didn't push before migrating SDD and SCT.
FYI, I still plan to make more improvements, in particular on the computed is_sepa field: I want to add an additional check on the IBAN prefix, to make sure that the country is part of the SEPA zone (for example, Turkey uses IBAN, but is not part of the SEPA zone, cf the map on https://en.wikipedia.org/wiki/Single_Euro_Payments_Area).
And I would also like to rework the XML generation.

I don't want to make a simple port, I want to go further than that. But, for those who need to go live on January 1st 2021, they can start to use this code.

**Comment by pedrobaeza** [comment]
OK, what kind of rework on XML generation are you thinking about?

**Comment by CarlosRoca13** [comment]
Please, close this PR and add the new features in other PR that makes the Improvement. https://github.com/OCA/bank-payment/pull/761 was merged yesterday

**Pull request closed without merging**
