### PR TITLE
[13.0][IMP] account_payment_order - Split method create_account_payment_line for better inheritability

### PR DESCRIPTION
**Pull request by ghost**
In the current logic, if we want to change the applicable lines to add in a payment order trough the actions available on a move, we have to inherit the full method. We suggest to split the method create_account_payment_line in two for better inheritability of that logic.

In our customer case, we repurpose the Purchase Receipts and we want the purchase receipt lines to be added in the payment orders. The move lines to be added are not using a receivable or payable account.

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Great to see you on OCA !

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
/ocabot merge patch

Please check if FW port is needed

**Pull request merged**
