### PR TITLE
[WIP][FIX] Fix travis issues - coding header and manifesto version.

### PR DESCRIPTION
**Pull request by NL66278**
Solve travis issues, to make PR's green again.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Only a few more to get a green build:
```
account_banking/account_banking.py:222:1: E305 expected 2 blank lines after class or function definition, found 0
account_banking/account_banking.py:289:1: E305 expected 2 blank lines after class or function definition, found 0
account_banking/parsers/convert.py:46:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking/sepa/postalcode.py:186:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_fi_patu/parser.py:252:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_make_deposit/report/deposit_ticket.py:37:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_mt940/mt940.py:230:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_uk_hsbc/mt940_parser.py:169:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_uk_hsbc/wizard/paymul.py:549:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_uk_hsbc/wizard/paymul_test.py:299:1: E305 expected 2 blank lines after class or function definition, found 1
account_banking_sepa_direct_debit/__openerp__.py:22: [C8106(manifest-version-format), ] Wrong Version Format "0.2" in manifest file. Regex to match: "(7.0)\.\d+\.\d+\.\d+"
```

**Comment by NL66278** [comment]
@pedrobaeza Travis is satisfied now. Took some work, as solving some issues seemed to trigger more tests.

**Comment by NL66278** [comment]
No idea why runbot fails, it seems an error in runbot rather then in the branch.

**Review by pedrobaeza — APPROVED** [review]
Wow, such a hard work you have made! Thank you very much. Runbot has warning, so no worries for that. Fast-tracking this.

**Pull request merged**
