### PR TITLE
[14.0][FIX] Fire trigger only when purchase_vendor_bill field has been changed

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Makes sense

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
I think you have to change instead `new_mode` and `new_bank` variables for not assigning current one if no new is set.

**Comment by dreispt** [comment]
@ChrisOForgeFlow Can you comment on Pedro's question please?

**Comment by ChrisOForgeFlow** [comment]
> I think you have to change instead `new_mode` and `new_bank` variables for not assigning current one if no new is set.

I'm not sure if payment_mode_id should be changed with empty value(Empty values of new_move, new_bank), because that I tried to fire change  only when field purchase_vendor_bill_id is assigned, otherwise the field will be empty even when the onchange is fired by an empty field, like purchase_id

Because that I think that change only be triggered when field is not empty

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow Can you comment on Pedro's question please?

Done, thanks

**Comment by pedrobaeza** [comment]
That's not what I was saying. I want to avoid such convoluted code for not changing what is not needed.

**Comment by pedrobaeza** [comment]
The proper fix IMO is #955, that is already in 13.0. Can we close this one in favor of the other?

**Comment by pedrobaeza** [comment]
Closing in favor of #955 as no more comments.

**Pull request closed without merging**
