### PR TITLE
[IMP] account_banking_pain_base: switch from @api.model to @api.multi

### PR DESCRIPTION
**Pull request by sebalix**
The calls are the following:
`generate_payment_file()` -> `generate_party_block(...)` -> `generate_party_agent(...)`

The first was decorated with `api.multi` (with ensure_one) and the others with `api.model`.

This change allows to get the reference of the current payment order in
`generate_party_block(...)` and `generate_party_agent(...)` methods (for
instance to modulate the generation of the file depending on the related
payment method configuration).

Used by: https://github.com/OCA/l10n-switzerland/pull/558

### CODE REVIEW

**Comment by pedrobaeza** [comment]
OK for me in the general principle, but:

- Don't add `self.ensure_one()`. Maybe you are passing a multi-record or want to in a future implementation. As current code is not limited to one record, it doesn't make sense.
- Remove `@api.model` instead of changing it to `@api.multi`. The default is this last one.

**Comment by sebalix** [comment]
@pedrobaeza done

**Review by pedrobaeza — APPROVED** [review]

**Review by astirpe — APPROVED** [review]
Ok to remove the `self.ensure_one()` but then remember to adapt the code in `l10n_ch_pain_base` (https://github.com/OCA/l10n-switzerland/pull/558/files#diff-5d36e3d6e4ebf67a6a0490d4a52478d0R71).

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
