### PR TITLE
8.0 use sale_ok and purchase_ok filters in partner/sale/purchase form views

### PR DESCRIPTION
**Pull request by alexis-via**
Use widget=selection for payment_mode_id fields
Update demo data

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This way, we mimick payment term behaviour.

:+1:

**Comment by StefanRijnhart** [comment]
Does this mean that I cannot add a payment type to a customer refund?

**Comment by sbidoul** [comment]
@StefanRijnhart not sure to understand your question. 

These domains mean that only payment modes allowed for sale (sale_ok) are visible on customer invoices, and only payment modes allowed for purchase (purchase_ok) are visible on supplier invoices.

**Comment by StefanRijnhart** [comment]
If I have a customer refund, I might want to add it to a credit transfer. Customer refunds share the customer invoice form view. With this change, I cannot select a credit transfer payment mode on the invoice, if I understand correctly. Maybe the patch can take the invoice type into account.

**Comment by alexis-via** [comment]
@StefanRijnhart 
You point seems valid, but the problem is already present with the current code ; it's not specific to this PR.

**Comment by pedrobaeza** [comment]
Yeah, sale_ok and purchase_ok is not the problem. The problem comes from the domain apply adding invoices to the payment order. Sometime ago, Stefan, I ask you in 7.0 if refunds are included in a PR you made. As me, you didn't know because the code was not yours. Migrating the set to v8, I found that the problem exists, but I made only a port because of the hurry.

We should treat this problem, but on another issue.

**Comment by StefanRijnhart** [comment]
Right! Thanks for your comments. :+1: then.

**Comment by sbidoul** [comment]
So I merge this one.

@pedrobaeza would you create an issue to track your comment https://github.com/OCA/bank-payment/pull/103#issuecomment-71017335 above?

**Pull request merged**
