### PR TITLE
[11.0] [MIG] account_payment_partner

### PR DESCRIPTION
**Pull request by etobella**
Migration to 11.0.

Depends on:
- [x] account_payment_mode #399 

Still working on tests and multicompany environments

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@etobella check how I have put the description for have a bulleted list for marking dependencies.

**Review by rgarnau — APPROVED** [review]
LGTM :+1:

**Comment by JordiBForgeFlow** [comment]
Added tests + minor fixes here https://github.com/etobella/bank-payment/pull/3

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review.

**Pull request merged**
