### PR TITLE
[15.0][MIG] account_banking_pain_base

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by TeoGoddet — CHANGES_REQUESTED** [review]
It seems you shipped a lock file with your PR 
https://github.com/OCA/bank-payment/pull/885/files#diff-32eecf2ed4ab5ffaad373ef343721eefa6fd9b56c9b6dfb15b572e4f3cd661b2

**Comment by HaraldPanten** [comment]
@alexis-via account_payment_order has been merged. You can continue with this one 👍

**Comment by HaraldPanten** [comment]
Hi @alexis-via Will you continue this PR, or do you prefer us to supersede this one by another one?

THX!

**Comment by HaraldPanten** [comment]
Superseded by https://github.com/OCA/bank-payment/pull/912

**Pull request closed without merging**
