### PR TITLE
[ADD]account banking not required

### PR DESCRIPTION
**Pull request by gonxi**
This module add a check in payment mode for do bank account optional.
We talk about this in the Code sprint from Spain

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for this, but I think it should be a part of the main module: account_banking_paymente_export. There's not too much sense to need to install another module that makes something optional. What do you think?

Please sign the CLA.

**Comment by gonxi** [comment]
i have thought that all people don't want have bank account optional, only some, but is not problem for me do the changes in: account_banking_payment_export and do the
 PR in this module.
If you view better i can do in this module.

**Comment by pedrobaeza** [comment]
For those who don't want it, just keep the corresponding mark checked. Put the default to be mandatory and there won't be any difference with current situation.

Regards.

**Comment by gonxi** [comment]
OK! close this PR and  i will do this changes in account_banKing_payment_export

**Pull request closed without merging**
