### PR TITLE
8.0 Use attachments instead of creating a specific object for each payment file

### PR DESCRIPTION
**Pull request by alexis-via**
This is the rescue PR of the previous PR that went out of control after a git rebase.

### CODE REVIEW

**Comment by alexis-via** [comment]
I let the git experts do the rebase work this time, I won't do it myself. It's not easy to do, because you have to merge a patch on a file that I deleted in this branch :)

**Comment by sbidoul** [comment]
Original PR was in #117

**Comment by sbidoul** [comment]
I agree with the code and I tested it works fine. Before merging I assume we need the migration script.

**Comment by alexis-via** [comment]
By the way, the module account_banking_fr_lcr has been ported to v8 and moved to l10n-france with the attachement approach (no dedicated object to store the file).

**Comment by alexis-via** [comment]
@sbidoul I just contributed the migration scripts for SEPA Direct debit and SEPA Credit transfer, with the very kind help of @bwrsandman and @legalsylvain

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
Does this remove the unidecode requirement from travis?

https://github.com/OCA/bank-payment/blob/8.0/.travis.yml#L23

**Comment by alexis-via** [comment]
@bwrsandman no, we still need unidecode() in account_banking_pain_base/models/banking_export_pain.py

**Comment by bwrsandman** [comment]
ok :+1:

**Comment by sebastienbeau** [comment]
:+1: thanks for the job

**Pull request merged**
