### PR TITLE
7.0 camt improvements

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port of https://code.launchpad.net/~therp-nl/banking-addons/7.0-camt_improvements/+merge/224449

### CODE REVIEW

**Comment by hbrunn** [comment]
looks good! But could you merge from upstream and resolve the resulting conflicts?

**Comment by StefanRijnhart** [comment]
Thanks for the review! Conflicts are resolved now.

**Comment by hbrunn** [comment]
:+1:

**Comment by bwrsandman** [comment]
As this is pretty old, would you mind rebasing (or amending the last commit) in order to trigger travis tests.

Thank you

**Comment by max3903** [comment]
:+1:

**Comment by lfreeke** [comment]
:+1: (test)

**Pull request merged**
