### PR TITLE
[REF] account_banking: replace eval() with getattr()

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by antespi** [comment]
:+1:

**Comment by gurneyalex** [comment]
probably should be closed (cf. #248)

@StefanRijnhart do you confirm?

**Comment by pedrobaeza** [comment]
Yes, I close it and propose the removal in other PR.

**Pull request closed without merging**
