### PR TITLE
[DEL] No more any need for porting account_iban_preserve_domestic.

### PR DESCRIPTION
**Pull request by NL66278**
```
- IBAN is now required for all countries/banks using IBAN accounts.
```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
That was quick... You should also remove **unported**/account_banking_iban_lookup, which depends strongly on the domestic module. **unported**/account_banking_nl_clieop can be removed as well. Then there is a snippet in **unported**/account_banking/res_partner_bank.py which uses the field 'acc_number_domestic' if available.

**Comment by pedrobaeza** [comment]
@StefanRijnhart, can you make the PR, please?

**Comment by StefanRijnhart** [comment]
@NL66278 is working on this for Therp at this moment, so I hope he will follow this up.

**Comment by pedrobaeza** [comment]
Thanks! :smile:

**Pull request merged**
