### PR TITLE
[12.0][IMP] account_banking_mandate: Improve code to unify search of valid mandate

### PR DESCRIPTION
**Pull request by carlosdauden**
ping @chienandalu 

@Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by victoralmau — APPROVED** [review]

**Comment by carlosdauden** [comment]
Don't merge yet, I will improve tests

**Comment by carlosdauden** [comment]
Tests improved

**Comment by carlosdauden** [comment]
Ready to merge

**Review by HaraldPanten — APPROVED** [review]
tests improved 👍

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please fw-port it to 13/14

**Pull request merged**
