### PR TITLE
[FIX] Issue #228 Error when table to be migrated does not exist.

### PR DESCRIPTION
**Pull request by NL66278**
See #228 Problem when table sdd_mandate does not exit during migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Does this still applies?

**Comment by NL66278** [comment]
I think it still does, anyway I think it is always good when migrating to test wether the stuff to be migrated is actually there.

**Comment by pedrobaeza** [comment]
Can you check falke8 errors and I'll merge?:

```
account_banking_sepa_direct_debit/migrations/0.2/post-consolidation.py:37:33: W291 trailing whitespace
account_banking_sepa_direct_debit/migrations/0.2/post-consolidation.py:55:79: E502 the backslash is redundant between brackets
```

**Comment by NL66278** [comment]
Flake8 corrections done.

**Comment by pedrobaeza** [comment]
OK, there are now a lot of other flake8 errors, but they are due to the new check that is being made, so I merge this one.

**Pull request merged**
