### PR TITLE
[10.0][IMP] account_banking_pain_base: Allow overriding initiating pa…

### PR DESCRIPTION
**Pull request by rousseldenis**
…rty name

### CODE REVIEW

**Comment by rousseldenis** [comment]
@alexis-via @OCA/accounting-maintainers

**Review by grindtildeath — APPROVED** [review]

**Comment by rousseldenis** [comment]
@grindtildeath Thanks ! :-)

**Review by dreispt — APPROVED** [review]

**Review by FrancoMaxime — COMMENTED** [review]
LGTM

**Pull request merged**
