### PR TITLE
[IMP] _columns deprecated

### PR DESCRIPTION
**Pull request by rlizana**

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: LGTM

**Comment by pedrobaeza** [comment]
Thanks for the change, Roberto. This is one of the less modules that I didn't touch for the migration, and now there is a better option for doing this: you can declare the field as usual (fields.Selection) and add the attribute `extend_selection=` with the new value/s for the selection, and there's no need to make this little hack.

**Comment by rvalyi** [comment]
@pedrobaeza you are right indeed I had forgotten that one.

**Comment by StefanRijnhart** [comment]
Thanks Roberto. I missed your proposal before but it is now obsolete by this commit https://github.com/OCA/bank-payment/commit/9ad1dd94a249f2e45342fa733b64bb693b0fdda6

**Pull request closed without merging**
